project(wordpress-plugin): Primera version OA y README
Laboratoria/bootcamp pull request #1083
Opened 2021-07-14 11:41 UTC by ssinuco

project(wordpress-plugin): Primera version de objetivos de aprendizaje y README. Pendiente completar las seciones "Consideraciones generales" y "Criterios de aceptación mínimos del proyecto".

2021-07-16 10:55 UTC, lupomontero reviewed
Muchas gracias por el PR @ssinuco y @adolivaresl :raised_hands: 

En líneas generales, objetivos de aprendizaje y boilerplate, creo que está súper.

He dejado algún comentario y varias sugerencias de cambios (la mayoría typos o detalles de redacción, nada grave :relieved:).

Quedo a la espera de que puedan revisar los comentarios/sugerencias y de ahí procedemos con el _merge_ :rocket:

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +> Los sistemas de gestión de contenidos o CMS (Content Management System)  son
```suggestion
> Los sistemas de gestión de contenidos o CMS (Content Management Systems) son
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +> Wordpress es uno de los CMS más utilizados en el mercado, éste permite crear
```suggestion
> Wordpress es uno de los CMS más utilizados en el mercado. Éste permite crear
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +> blogs personales u otro tipo de páginas web como webs corporativas, revistas,
```suggestion
> blogs personales u otro tipo de sitios web, como páginas corporativas, revistas,
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +> tiendas online, periodicos digitales, etc(aquí te dejamos Wordpress Website
Acá me da la impresión de que falta convertir el texto _Worpress Website Showcase_ a un link que nos lleve al showcase, no?

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +> es un lenguaje de código abierto [más populares desde el lado del servidor (79.2%)](https://w3techs.com/technologies/overview/programming_language)
```suggestion
> desarrolladores. El lenguaje en el que desarrollamos Wordpress es PHP,
> que es el lenguaje de código abierto [más popular desde el lado del servidor (79.2%)](https://w3techs.com/technologies/overview/programming_language)
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +> Los sistemas de gestión de contenidos o CMS (Content Management System)  son
Veo que el contenido del _preámbulo_ está en un `<blockquote>`... se trata de una cita de algún otro recurso? En caso de que lo sea, sería bueno agregar fuente (con link). Si no es una cita, propondría quitar el `<blockquote>`... :thinking:

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +> Wordpress es uno de los CMS más utilizados en el mercado, éste permite crear
Al ser la primera mención de Wordpress, quizás también haría que la palabra _Wordpress_ sea un link a la página oficial.

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +exactamente cuál será el alcance de tu proyecto y que objetivos de aprendizaje
```suggestion
exactamente cuál será el alcance de tu proyecto y qué objetivos de aprendizaje
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +> Wordpress es uno de los CMS más utilizados en el mercado, éste permite crear
También me acabo de dar cuenta de que en las páginas _oficiales_ siempre usan _WordPress_ en camel case. Propongo hacer un find-and-replace para asegurarnos de que todas las menciones a WordPress usen esa convención. Ahora a veces aparece como Wordpress y otras como WordPress.

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +En la carpeta ```php-playground``` puedes crear tus archivos PHP de práctica y ejecutarlos
```suggestion
En la carpeta `php-playground` puedes crear tus archivos PHP de práctica y ejecutarlos
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +[http://localhost:8080](http://localhost:8080). Por ejemplo en esta carpeta ya
```suggestion
[http://localhost:8080](http://localhost:8080). Por ejemplo, en esta carpeta ya
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +esta creado el archivo [```hola.php```](http://localhost:8080/hola.php)
```suggestion
está creado el archivo [`hola.php`](http://localhost:8080/hola.php)
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +[WordPress API](https://codex.wordpress.org/WordPress_APIs)
```suggestion
* Usar al menos una
[API ofical de WordPress](https://codex.wordpress.org/WordPress_APIs)
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +Sin embargo también es posible usar librerías como
```suggestion
Sin embargo, también es posible usar librerías como
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +Te invitamos a que evalues cada alternativa y decidas cúal es la más apropiada
```suggestion
Te invitamos a que evalúes cada alternativa y decidas cúal es la más apropiada
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +    Esto ejecuta ```docker-compose up``` en modo detached, descarga las
```suggestion
    Esto ejecuta `docker-compose up` en modo detached, descarga las
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +En caso en que necesites usarlo, puedes ejecutarlo con el siguiente comando:
```suggestion
Si quieres o necesitas usarlo, puedes ejecutarlo con el siguiente comando:
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +PHP para declarar variables, usar condicionales y estructuras de control y
```suggestion
PHP para declarar variables, usar condicionales, estructuras de control y
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +En la carpeta ```php-playground``` puedes crear tus archivos PHP de práctica y
```suggestion
En la carpeta `php-playground` puedes crear tus archivos PHP de práctica y
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +Por ejemplo en esta carpeta ya esta creado el archivo ```hola.php``` como se
```suggestion
Por ejemplo en esta carpeta ya esta creado el archivo `hola.php` como se
```

2021-07-16 10:55 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +En este ya podrás comenzar a desarrollar tu plugin para WordPress. Puedes
```suggestion
En este punto, ya podrás comenzar a desarrollar tu plugin para WordPress. Puedes
```

2021-07-16 18:58 UTC, lupomontero approved these changes
LGTM :star2:

2021-07-27 16:51 UTC, oxfist requested changes
Hice algunos comentarios puntuales sobre la redacción del README, y por otro lado me surgen dos cuestiones más generales viendo el proyecto:

### 1. Sobre el alcance del proyecto

Considerando los OAs específicos de PHP y de WordPress hago la pregunta, ¿consideramos que esto podría ser trabajable en 2-3 semanas?

Considero que es poco tiempo para enfrentarse a un lenguaje de programación completamente nuevo y sobre eso una herramienta con su propia lógica (CMS) y ecosistema como lo es WordPress, donde junto a lo anterior ponemos el desarrollo de un plugin, que ese plugin esté enfocado en una problemática definida por las estudiantes y además implementar pruebas unitarias.

Creo que podríamos ser un poco más generosas y **sugerir en cambio 4-5 semanas**, considerando:
1. Las complejidades de enfrentar esto solas o con la comunicación requerida si es en duplas
2. Aprendizajes y bloqueos inesperados
3. Darnos un margen para validar esa estimación

Junto a lo anterior creo que si las estudiantes van a ocupar Docker solo para instalar WordPress y para levantar el servicio en su flujo normal, podríamos guiar un poco más eso y **evitarnos agregarlo OAs relacionados con Docker**, pues considero que reporta complejidades y conceptos que en la práctica terminarían quedando fuera.

### 2. Qué tan general o específicos hacer los OAs

Esto es algo que me surge con los OAs de la currícula en general, pero a mí personalmente me cuesta identificar un alcance para cada uno, pues al tenerlo como una descripción sobre características de un lenguaje o plataforma, o en el caso de WordPress como "módulos" de la aplicación o ciertas funcionalidades (ej. "Menus de administración", "Configuraciones", "Usuarios") creo que es difícil enfocarlo a un resultado esperable, ¿qué esperaríamos que las estudiantes puedan hacer una vez cubierto el OA "Menús de administración"? Podría ser quizás muy subjetivo.

Para esto se me ocurría que podíamos quizás enfocar los OAs en la capacidad/habilidad de realizar una tarea utilizando la tecnología correspondiente, en este caso "Menus de administración" podría estar más enfocado en "Crear menús de administración para un plugin nuevo" y/o "Configurar plugin a través de menús de administración", de esta forma es más claro qué debieran conseguir y de ahí vendría la secuencia de:
1. familiarizarse con el módulo o funcionalidad primero (leyendo documentación), y
2. tratar de aplicar eso para resolver un problema.

2021-07-27 16:51 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +que es el lenguaje de código abierto [más popular desde el lado del servidor (79.2%)](https://w3techs.com/technologies/overview/programming_language)
Aquí también agregaría la fuente, pues "el más popular" siempre es algo debatible jeje, de hecho el estudio de [StackOverflow del 2020](https://insights.stackoverflow.com/survey/2020#technology-programming-scripting-and-markup-languages) por ejemplo pone a PHP en 8vo lugar.

```suggestion
que es el lenguaje de código abierto [más popular desde el lado del servidor (79.2%)](https://w3techs.com/technologies/overview/programming_language), según un estudio de W3Techs.com.
```

2021-07-27 16:51 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +cubrirás. Define un alcance que te tome de 2 a 3 semanas como máximo.
Dejo arriba un comentario más general sobre el tiempo estimado, pero propondría el doble de tiempo.
```suggestion
cubrirás. Define un alcance que te tome de 4 a 5 semanas como máximo.
```

2021-07-27 16:51 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +#### `apache2`
¿Creen que sería bueno dar un poco más de contexto sobre el rol que un servidor web, específicamente Apache aquí, cumple con una herramienta como WordPress? Si bien no sería necesario que modifiquen nada las estudiantes, quizás valdría la pena poner un pequeño diagrama con las cajitas que serían la arquitectura de este proyecto. La otra opción que se me ocurre es ponerlo al final, por un tema de jerarquía de la información, para que sepan no es el que requiere más atención.

2021-07-27 16:51 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +[acá](https://www.wpbeginner.com/beginners-guide/beginners-guide-to-wordpress-file-and-directory-structure/).
No tengo mucha idea sobre cómo se estructura un proyecto en WordPress, pero me fijé que el link es del 2016. ¿Será la versión más actualizada? Si no puede llevar a confusión a las estudiantes.

2021-07-27 16:51 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +### Pruebas unitarias
Creo que si a lo anterior sumamos tests unitarios el alcance queda muy grande, quizás es buena idea revisar el alcance de lo esperado con el plugin, o sobre el trabajo con PHP y si es que es factible incorporar la utilización de PHPUnit para los tests de este proyecto.

2021-07-27 16:51 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +[Docker Compose](https://docs.docker.com/compose/).
Si esta es la primera vez que las estudiantes se van a enfrentar a Docker y Docker Compose creo que podríamos guiar un poco más esto. Quizás no es necesario ahondar en qué es Docker y cómo funciona pero sí poner los pasos de instalación sin que tengan que pasar ellas por la documentación, pues veo una complejidad adicional que podría no reportar tanto valor aquí.

2021-07-27 16:51 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +* [Getting started with Docker Composer](https://docs.docker.com/compose/gettingstarted/)
A partir del foco que este proyecto tendría creo que puede no ser necesario agregar documentación de Docker si guiamos un poco más la instalación, así no habría que ahondar mucho más, pues pienso que puede ser algo que saque a las estudiantes del foco del proyecto.

2021-07-27 16:51 UTC, oxfist commented on projects/05-wordpress-plugin/project.yml
> +learningObjectives:
En esta parte viendo los OAs creo que puede ser mucho agregar Docker. Si guiamos un poco más la instalación y el uso en el flujo de desarrollo creo que podemos evitarnos ahondar en eso en este proyecto para que se enfoquen más en adentrarse en arquitectura cliente-servidor, PHP como nuevo lenguaje y WordPress en sí.

2021-07-27 20:07 UTC, lupomontero commented
## 1. Sobre el alcance del proyecto

> Considerando los OAs específicos de PHP y de WordPress hago la pregunta, ¿consideramos que esto podría ser trabajable en 2-3 semanas?

:+1: Pensándolo bien, creo que sería buena idea ser un poco más generosos con el tiempo, teniendo en cuenta nuevo lenguaje, nuevo stack, etc...

> [...] si las estudiantes van a ocupar Docker solo para instalar WordPress y para levantar el servicio en su flujo normal, podríamos guiar un poco más eso y evitarnos agregar los OAs relacionados con Docker [...]

:+1: De acuerdo que el foco debería estar en el lado de WordPress/PHP y no `docker` y/o `docker-compose` ... quizás tenga sentido agregar un poco más de granularidad a los OAs relacionados a `docker` para que exista algo muy básico que solo incluya  `run`, `ps`, `logs` y `exec` por ejemplo... sin tener que entrar en cómo configurar y conectar los diferentes  contenedores... (redes, volúmenes, etc, ...).

***

## 2. Qué tan generales o específicos hacer los OAs

> [...] se me ocurría que podíamos quizás enfocar los OAs en la capacidad/habilidad de realizar una tarea utilizando la tecnología correspondiente, en este caso "Menus de administración" podría estar más enfocado en "Crear menús de administración para un plugin nuevo" y/o "Configurar plugin a través de menús de administración" [...]

Desde mi punto de vista, creo que la pregunta que debemos hacernos es si dichos _subobjetivos_ aparecerán alguna vez por separado. Si la respuesta es por ahora no, optaría por mantener ambas cosas bajo el mismo paraguas y así terminar con la lista más corta que tenga sentido (pudiendo agregar links a puntos más granulares y/o una descripción - que todavía no estamos usando :see_no_evil:). Por otro lado, si la respuesta es probablemente sí, en el corto plazo, entonces creo que sí tiene valor presentarlos por separado... :thinking: 

@ssinuco, como lo ves? ¿Crees que tenga sentido agregar un poco más de granularidad desde el punto de vista de tareas concretas como propone @oxfist?

cc/ @adolivaresl @fakel @diegovelezg @alejandrarv

2021-07-28 19:57 UTC, ssinuco commented on projects/05-wordpress-plugin/README.md
> +#### `apache2`
Creo que si hablamos de servidores web estariamos agregando un tema más para aprender a las estudiantes y podriamos distraerlas de los objetivos principales que son PHP y WordPress. Tal vez podria mencionarse en un Q&A del proyecto por las coaches.

2021-07-28 19:58 UTC, ssinuco commented on projects/05-wordpress-plugin/README.md
> +[acá](https://www.wpbeginner.com/beginners-guide/beginners-guide-to-wordpress-file-and-directory-structure/).
Si, la estructura de carpetas no ha cambiado, el articulo sigue siendo valido.

2021-07-28 20:02 UTC, ssinuco commented on projects/05-wordpress-plugin/README.md
> +### Pruebas unitarias
Las pruebas unitarias se mencionan como un criterio mínimo de aceptación del proyecto para continuar "sembrando" en las estudiantes que idealmente cualquier código que escriban deberian tener pruebas. Ahora tal vez pedir un 70% de cobertura sea demasiado. ¿Que les parece si lo bajo al 30%? 

Por otro lado, practicamente para hacer pruebas unitarias en PHP se esta obligado a usar PHPUnit.

2021-07-28 21:12 UTC, ssinuco commented on projects/05-wordpress-plugin/README.md
> +[Docker Compose](https://docs.docker.com/compose/).
Estoy de acuerdo. En este proyecto no es necesario que las estudiantes aprendan Docker y Docker Compose. De hecho usamos Docker porque tampoco queriamos complicarlas con la instalacion de apache/nginx, mysql y PHP. Retiraré los links de la documentacion oficial de Docker.

2021-07-28 21:14 UTC, ssinuco commented on projects/05-wordpress-plugin/project.yml
> +learningObjectives:
De acuerdo los retiro porque no son el foco del proyecto.

2021-07-28 21:16 UTC, ssinuco commented on projects/05-wordpress-plugin/README.md
> +* [Getting started with Docker Composer](https://docs.docker.com/compose/gettingstarted/)
De acuerdo. Agregaré un link a un video donde se explique la instalacion de docker y docker compose tanto en linux como en windows.

2021-07-28 21:29 UTC, ssinuco commented
> +1 Pensándolo bien, creo que sería buena idea ser un poco más generosos con el tiempo, teniendo en cuenta nuevo lenguaje, nuevo stack, etc...

@lupomontero de acuerdo, lo cambie a entre 4 y 5 semanas tal como lo sugirió @oxfist 

> +1 De acuerdo que el foco debería estar en el lado de WordPress/PHP y no `docker` y/o `docker-compose` ... quizás tenga sentido agregar un poco más de granularidad a los OAs relacionados a `docker` para que exista algo muy básico que solo incluya `run`, `ps`, `logs` y `exec` por ejemplo... sin tener que entrar en cómo configurar y conectar los diferentes contenedores... (redes, volúmenes, etc, ...).

@lupomontero retiré los objetivos de aprendizaje relacionados con Docker. Creo que distraen a las estudiantes. Finalmente solo usamos Docker para no complicarlas con la instalacion de un LAMP.

> @ssinuco, como lo ves? ¿Crees que tenga sentido agregar un poco más de granularidad desde el punto de vista de tareas concretas como propone @oxfist?
> 

Soy partidario de dejar los OA de forma general y acotarlos en el README de cada proyecto. Creo que los OA de este proyecto se aterrizan bastante en la seccion "5. Criterios de aceptación mínimos del proyecto", subseccion "Funcionalidades mínimas". Si consideran necesario, podria detaller mas esta sección.

2021-07-28 21:30 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +### Pruebas unitarias
Súper de acuerdo con lo de PHPUnit y lo de los tests como criterio mínimo. Pienso que más que un porcentaje fijo quizás podemos llevar a que ciertas partes del plugin estén testeadas, _a priori_ me parece que es difícil saber cuánto será ese porcentaje, entonces más que contrastar contra ese porcentaje de cobertura se podría guiar a que las estudiantes tengan las funciones y/o clases más importantes de su plugin testeadas.

Una forma de guiar esto podría ser hablar de que "las principales funcionalidades de tu plugin, sin considerar el código que se integra con WordPress, debería estar cubierto por pruebas unitarias". 🤔

2021-07-28 21:33 UTC, oxfist commented on projects/05-wordpress-plugin/README.md
> +Wix(1.7%)](https://w3techs.com/technologies/overview/content_management), según un estudio de 2021 de W3Techs.com.
Esto debería arreglar el error del linter

```suggestion
Wix(1.7%)](https://w3techs.com/technologies/overview/content_management),
según un estudio de 2021 de W3Techs.com.
```

2021-07-30 17:56 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +#### `apache2`
Quizás sería bueno agregar un poco de contexto (1-2 parrafitos) introduciendo la idea de qué es un servidor web y dónde calza en el caso de una aplicación como WordPress...

Para no seguir alargando este PR me he tomado la libertad de crear un issue para hacer seguimiento de este punto: #1091

2021-07-30 19:36 UTC, lupomontero commented on projects/05-wordpress-plugin/README.md
> +### Pruebas unitarias
Continúa acá: #1093

2021-07-30 19:40 UTC, merged

2021-08-02 12:30 UTC, lupomontero commented
@all-contributors please add @ssinuco for content and code