project(data-lovers): Adds new data set (harry potter)
Laboratoria/bootcamp pull request #1137
Opened 2022-01-18 23:04 UTC by danielislas3

He agregado un nuevo set de datos sobre Harry Potter ⚡🧙, la traducción del readme para portugués la hice con google translate. Seria bueno darle una revisada  👀

2022-01-20 18:24 UTC, gabrieluizramos requested changes
Gracias! ⭐ 

Dejo apenas alguns pequenos comentarios.

2022-01-20 18:24 UTC, gabrieluizramos commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +centra-se na luta entre Harry Potter e o malvado feiticeiro Lord Voldemort,
"O argumento é centra-se na luta entre Harry Potter e o malvado feiticeiro Lord Voldemort" podemos mudar para "O enredo é foca na luta entre Harry Potter e o malvado feiticeiro Lord Voldemort"

2022-01-20 18:24 UTC, gabrieluizramos commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +O sucesso das novelas fez da marca uma das mais bem sucedidas do mundo.
"das novelas" talvez trocar para "da saga".

2022-01-20 18:24 UTC, gabrieluizramos commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +Fazendo pesquisas sobre as informações que eles podem precisar
Falta uma vírgula após `precisar`, seria `eles podem precisar, nossos usuários`.

2022-01-20 18:24 UTC, gabrieluizramos commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +  Quantos alunos há em cada casa?
Sinto que essa frase perdeu um pouco o sentido. Poderíamos remover o `?` no final e transformar o `Q` em minúsculo: `Nossos usuários estão interessados ​​em saber quantos alunos há em cada casa.`

2022-01-20 18:24 UTC, gabrieluizramos commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +\ que os personagens podem invocar, também o lugar no livro onde eles estão
Acho que essa `\` tá sobrando. Podemos remover.

Além disso, podemos reformular essa frase para algo como: `também o lugar no livro onde eles estão e a pronúncia do feitiço.`

2022-01-20 18:28 UTC, mfdebian reviewed
Sólo un par de cambios pequeños, lo demás todo parece estar okey! :rocket: :stars:

2022-01-20 18:34 UTC, JulianaAmoasei commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +Harry Potter é uma série de romances de fantasia escritos pelo autor
"pela autora"

2022-01-20 18:36 UTC, JulianaAmoasei commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +britânica J. K. Rowling, que descreve as aventuras da jovem
"britânica J. K. Rowling, que descreve as aventuras da jovem feiticeiro da bruxaria e feitiçaria Harry Potter e seus amigos ao longo dos anos que acontecem na Escola de Magia e Bruxaria de Hogwarts."

Podemos mudar para "as aventuras do jovem bruxo Harry Potter e seus amigos ao longo dos anos em que passam estudando na Escola de Magia e Bruxaria de Hogwarts."

2022-01-20 18:38 UTC, JulianaAmoasei commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +Harry Potter e as Relíquias da Morte: Parte 2, estreou em 15 de julho
"estreou em 15 de julho 2011 e com oito filmes realizados, a série se tornou uma das franquias de filmes de maior sucesso em termos de receitas de bilheteria." 

Para
"estreou em 15 de julho de 2011 e, com oito filmes lançados, a série se tornou uma das franquias de filmes de maior sucesso em termos de receita de bilheteria."

2022-01-20 18:40 UTC, JulianaAmoasei commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +  estar preparado.
"o que eles fazem para estarem preparados."

2022-01-20 18:41 UTC, JulianaAmoasei commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +- Todas essas informações são baseadas na saga de romances da autora J. K. Rowling,
"- Todas essas informações são baseadas na saga de romances da autora J. K. Rowling,  para nossos usuários é importante saber quantos livros foram publicados e gostariam de poder visualizar quais personagens aparecem em cada livro."

Para:
"- Todas essas informações são baseadas na saga de livros da autora J. K. Rowling. Nossos usuários acham importante saber quantos livros foram publicados e gostariam de poder visualizar quais personagens aparecem em cada livro."

2022-01-20 18:43 UTC, JulianaAmoasei commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +  ter um dicionário para poder consultá-los é um pedido dos usuários.
"Poções são uma ferramenta crucial no mundo de Harry Potter, ter um dicionário para poder consultá-los é um pedido dos usuários."

Para:
"Poções são uma ferramenta crucial no mundo de Harry Potter e nossos usuários gostariam de ter um dicionário para poder consultá-las."

2022-01-20 18:44 UTC, JulianaAmoasei commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +## Detalhes da data
Acho que poderia ser "Detalhes dos dados"

2022-01-20 18:45 UTC, JulianaAmoasei commented on projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> +livro, bem como uma breve descrição do mesmo.
"do mesmo" -> "das mesmas"

2022-01-26 19:48 UTC, mfdebian commented
@all-contributors please add @JulianaAmoasei for review

2022-02-01 18:21 UTC, mfdebian approved these changes

2022-02-01 18:23 UTC, merged