Add deployment instructions for cipher and card validation projects
Laboratoria/bootcamp pull request #1152
Opened 2022-02-10 14:08 UTC by gabrieluizramos

Uno de los majores problemas con los proyectos iniciales (cipher & card-validation) para las estudiantes de SAP-007 fueron las instrucciones de como hacer lo deploy de lo proyecto.

Este PR adiciona una secion en los READMEs con instruciones.

2022-02-10 15:10 UTC, JulianaAmoasei commented
@gabrieluizramos há versões em pt-br e em es do link:
https://docs.github.com/pt/pages
https://docs.github.com/es/pages

Talvez valha a pena mesmo se estiver incompleta...

2022-08-08 16:18 UTC, mfdebian requested changes
@gabrieluizramos Com essas mudanças já devem passar nos testes!

2022-08-08 16:18 UTC, mfdebian commented on projects/01-card-validation/README.md
> +Hacer que los sitios estén publicados (o _desplegados_) para que usuarias de la web puedan acceder a él es algo común en proyectos de desarrollo de software.
```suggestion
Hacer que los sitios estén publicados (o _desplegados_) para que usuarias de
la web puedan acceder a él es algo común en proyectos de desarrollo de software.
```

2022-08-08 16:18 UTC, mfdebian commented on projects/01-cipher/README.md
> +Hacer que los sitios estén publicados (o _desplegados_) para que usuarias de la web puedan acceder a él es algo común en proyectos de desarrollo de software.
```suggestion
Hacer que los sitios estén publicados (o _desplegados_) para que usuarias de
la web puedan acceder a él es algo común en proyectos de desarrollo de software.
```

2022-08-08 16:27 UTC, mfdebian approved these changes

2022-08-08 17:34 UTC, merged

2022-08-08 17:35 UTC, mfdebian commented
Muito obrigado @gabrieluizramos!! :metal:  o PR já foi mergeado.