Uso de readFileSync y readdirSync
Laboratoria/bootcamp pull request #1219
Opened 2022-08-30 17:06 UTC by ssinuco

Se agrega al README explicitamente no permitir el uso de la funcion readFileSync y recomendar readdirSync para la recursión.

2022-09-01 19:18 UTC, unjust commented
@ssinuco Me gusta resaltar el punto de los metodos sincronos en este readme! 

No se si diria que`readdirSync` ayuda con la recursividad en si - pero si, los metodos sincronos puede simplificar su codigo. Deciamos a ellas que puede optar por los metodos `sync` para no tiene que trabajar tanto con callbacks (tambien puede utilizar versiones con promesas creo).

No estoy de acuerdo a prohibir `readFileSync`. He visto implementaciones que lo usa para obtener de contenido de file y de alli pasalo a un parser.

2022-09-02 14:11 UTC, mfdebian commented
En mi opinión, dada la naturaleza del proyecto, creo que el trabajar con asincronía **es uno de los principales objetivos**, si bien el proyecto _puede_ resolverse utilizando las variaciones `sync` de los métodos del módulo `fs`, la forma más correcta sería la de utilizar las versiones asíncronas, incluso "promisificando" la función `readFile`; En un ambiente de trabajo real, muy probablemente tendríamos que hacer ese trabajo (el de leer archivos) de manera asíncrona ya que existe el riesgo potencial de que un archivo sea _demasiado_ grande y eso cuelgue la ejecución del programa y queremos que las estudiantes se involucren con esas dinámicas, además que el concepto de asincronía, y también testeo de código asíncrono, se refuerza harto en este proyecto dado que son parte de sus Objetivos de Aprendizaje.

Con respecto a lo del uso de `readdirSync` dentro del contexto de la ejecución del loop recursivo también estoy de acuerdo! :blush:

2022-09-06 15:16 UTC, unjust commented on projects/04-md-links/README.md
> +* Para este proyecto **no está permitido** utilizar `readFileSync`.
No lo prohibiria. Quiza agrega un razon en cual momento no es recomendado.

2022-09-06 15:17 UTC, unjust commented on projects/04-md-links/README.md
> +**Recuerda**: no esta permitido usar `readFileSync`.
no lo prohibiria.

2022-09-06 16:15 UTC, mfdebian commented on projects/04-md-links/README.md
> +* Para simplificar la recursividad, te recomendamos usar `readdirSync`.
Creo que no afecta en sí al loop recursivo, pero sí ayuda a que esa función/algoritmo quede más simple y fácil de implementar, entiendo eso como la _intención_ del comentario en el README, podemos dejarlo como una sugerencia para esa implementación!

2022-09-06 16:15 UTC, mfdebian commented on projects/04-md-links/README.md
> +* Para este proyecto **no está permitido** utilizar `readFileSync`.
Dejémoslo como sugerencia entonces!

2022-09-06 16:15 UTC, mfdebian commented on projects/04-md-links/README.md
> +**Recuerda**: no esta permitido usar `readFileSync`.
Lo dejamos como sugerencia!

2022-09-06 16:59 UTC, mfdebian requested changes
Cambios sugeridos tomando el feedback de @unjust

2022-09-06 16:59 UTC, mfdebian commented on projects/04-md-links/README.md
> +* Para este proyecto **no está permitido** utilizar `readFileSync`.
```suggestion
* Para este proyecto te sugerimos **no utilizar** la versión síncrona de la función para leer archivos, `readFileSync`, y en cambio intentar resolver este desafío de manera asíncrona.
```

2022-09-06 16:59 UTC, mfdebian commented on projects/04-md-links/README.md
> +* Para simplificar la recursividad, te recomendamos usar `readdirSync`.
```suggestion
* Para disminuir la complejidad de tu algoritmo recursivo, te recomendamos utilizar la versión síncrona de la función para leer directorios, `readdirSync`.
```

2022-09-06 16:59 UTC, mfdebian commented on projects/04-md-links/README.md
> +**Recuerda**: no esta permitido usar `readFileSync`.
```suggestion
**Recuerda**: Te sugerimos **no utilizar** la versión síncrona de la función para leer archivos, `readFileSync`, y en cambio intentar resolver ese desafío de manera asíncrona.
```

2022-09-06 16:59 UTC, mfdebian commented on projects/04-md-links/README.md
> +que você usando `readdirSync`.
```suggestion
**Recuerda**: Para disminuir la complejidad de tu algoritmo recursivo, te recomendamos utilizar la versión síncrona de la función para leer directorios, `readdirSync`.
```

2022-09-06 16:59 UTC, mfdebian commented on projects/04-md-links/README.pt-BR.md
> +* Para este projeto, **não é permitido** o uso do `readFileSync`.
```suggestion
* Para este projeto, sugerimos que você **não use** a versão síncrona da função de leitura de arquivo, `readFileSync`, e tente resolver esse desafio de forma assíncrona.
```

2022-09-06 16:59 UTC, mfdebian commented on projects/04-md-links/README.pt-BR.md
> +**Lembrar**: não é permitido o uso do `readFileSync`.
```suggestion
**Lembrar**: Para este projeto, sugerimos que você **não use** a versão síncrona da função de leitura de arquivo, `readFileSync`, e tente resolver esse desafio de forma assíncrona.
```

2022-09-06 16:59 UTC, mfdebian commented on projects/04-md-links/README.pt-BR.md
> +* Para simplificar a recorrência, recomendamos o uso do `readdirSync`.
```suggestion
* Para diminuir a complexidade de seu algoritmo recursivo, recomendamos usar a versão síncrona da função de leitura do diretórios, `readdirSync`.
```

2022-09-06 16:59 UTC, mfdebian commented on projects/04-md-links/README.pt-BR.md
> +**Lembrar**: não é permitido o uso do `readFileSync`.
```suggestion
**Lembrar**: Para diminuir a complexidade de seu algoritmo recursivo, recomendamos usar a versão síncrona da função de leitura do diretórios, `readdirSync`.
```

2022-09-14 15:00 UTC, unjust commented
Gracias @ssinuco 🙏 ! Hay [algunos errores](https://github.com/Laboratoria/bootcamp/actions/runs/3046249515/jobs/4908826882) de `md linter`, puedes arreglarlos o quieres que te ayude?

2022-09-29 15:17 UTC, ssinuco commented
> Gracias @ssinuco pray ! Hay [algunos errores](https://github.com/Laboratoria/bootcamp/actions/runs/3046249515/jobs/4908826882) de `md linter`, puedes arreglarlos o quieres que te ayude?

Solucinado @unjust

2022-09-29 17:46 UTC, unjust approved these changes
LGTM! gracias @ssinuco

2022-09-29 19:21 UTC, mfdebian approved these changes

2022-09-29 19:22 UTC, merged