Fixes #1229 to add reference to commit in cohort
Laboratoria/bootcamp pull request #1230
Opened 2022-09-23 16:05 UTC by icarito

:thinking: this will leave a reference to the commit from where a cohort has been created to the end of the README.

2022-09-27 02:39 UTC, unjust commented on scripts/create-cohort-project.js
> +  const gitCommit = (await exec("git rev-parse HEAD")).stdout
podemos nombrar eso como `versionTag`  ? y falta una `;` a final de linea.

tambien no estoy familiarizado con `git rev-parse HEAD`... cuando lo corre en mi terminal me da el SHA de ultima commit. Mi expectativa es ver algo como v5.3.0, no se que estoy haciendo mal.

2022-09-27 02:39 UTC, unjust commented on scripts/create-cohort-project.js
> +      'ver: ' + gitCommit
quiza aqui podemos agregar un poco formato como `*** \n Bootcamp version: ` para dar un division de readme con un footer.

2022-09-30 14:50 UTC, unjust commented on scripts/create-cohort-project.js
> +  const gitCommit = (await exec("git rev-parse HEAD")).stdout
podemos usar el url exacto de bootcamp porque un remote puede tener cualquier nombre

2022-10-04 20:45 UTC, mfdebian commented
¡Mil gracias @icarito por el PR :blush: :raised_hands: !

Estoy de acuerdo con el comentario de @unjust en que quizás el comportamiento esperado es en realidad quizás poder ver el número de versión actual del repo más que el hash de un commit, que luego habría que ir a buscar.

Hice un pequeño cambio probando en mi máquina, dejándolo así:
`'Bootcamp version: ' + process.env.npm_package_version`

Aprovechando que el número de versión del `package.json` es el del release actual de la currícula, entonces al final se ve así:

![Screenshot_2022-10-04_17-38-59](https://user-images.githubusercontent.com/12631491/193923522-cfe4262d-d3a7-45a9-a9db-4a285c830a8a.png)

Voy a seguir haciendo algunas pruebitas, para ver si el lugar/momento donde está ocurriendo eso es el mejor y cómo dejar al final igual una _new line_ vacía, que es regla de [nuestro linter](https://github.com/Laboratoria/mdlint) de archivos markdown.

¡Nuevamente mil gracias a amb@s! :smile:  :yellow_heart:

2022-10-04 20:48 UTC, icarito commented
Gracias @mfdebian y @unjust - me pillaste sin alcanzar a hacer más cambios, era solo una prueba de concepto. Como no sabía que al versión NPM iba sincronizada (o pensaba que podría des-sincronizarse).

Te agradezco las pruebitas, de hecho no me quedaba claro donde poner metadata como esto excepto al pie del README, lo cual puede no ser lo mejor.

2022-10-04 20:51 UTC, icarito commented
Tal vez de hecho el mejor lugar para esta metadata podría ser el mismo `package.json` (del proyecto creado)?

2022-10-05 14:06 UTC, unjust commented
@icarito puede estar en el package.json  pero hay que avisar coaches que esta informacion esta alla entonces.

2022-10-26 12:28 UTC, icarito commented
Estupendo @mfdebian y @unjust, ha sido un gusto colaborar con Uds!

2022-10-26 17:40 UTC, unjust requested changes

2022-10-26 17:40 UTC, unjust commented on scripts/create-cohort-project.js
> +  let bootcamp_info = {
creo todo puede ser `const`

2022-10-26 17:40 UTC, unjust commented on scripts/create-cohort-project.js
> +  const gitCommit = (await exec("git rev-parse HEAD")).stdout
entonces ✂️ porque ya esta en `addBootcampInfo`

2022-10-26 17:41 UTC, unjust commented
@icarito hay algunos cambios antes que podemos hacer merge. deje en un review.

2022-10-26 17:42 UTC, unjust commented on scripts/create-cohort-project.js
> +      'ver: ' + gitCommit
✂️

2022-10-26 17:43 UTC, unjust commented
Para que recordamos ;-) Este seria el resultado final:
https://user-images.githubusercontent.com/12631491/197850505-83a6a2eb-02d2-47cb-97d3-88d88fad74b1.png

2022-10-27 16:19 UTC, lupomontero commented on scripts/create-cohort-project.js
> +  await fs.writeFile(projectPkgJsonPath, JSON.stringify(pkg, null, 2));
Siguiendo el _estilo_ ya existente en este repo, propondría algo así...

```suggestion
  const pkg = Object.assign(require(projectPkgJsonPath), {
    bootcamp: {
      createdAt: (new Date()).toISOString(),
      version: process.env.npm_package_version,
      commit: (await exec('git rev-parse HEAD')).stdout.trim(),
    },
  });
  await fs.writeFile(projectPkgJsonPath, JSON.stringify(pkg, null, 2));
```

Además de los cambios a nivel de estilo, cambiaría la representación de `createdAt` para que sea interpretable tanto a ojo por un ser humano como para la máquina (cadena ISO, por ejemplo `2022-10-27T16:15:15.268Z`).

:information_source: El método `String.prototype.trim` ya se encarga de quitar _whitespace_ alrededor de un _string_ (del principio y final).

:warning: El código de arriba lo he escrito directamente en el comentario y no lo he probado todavía :see_no_evil:

2022-11-02 18:46 UTC, unjust commented on scripts/create-cohort-project.js
> +  await fs.writeFile(projectPkgJsonPath, JSON.stringify(pkg, null, 2));
Gracias @lupomontero me parecen bien, me gusta tener el mismo estilo. A ver si @icarito quiere agregar algo mas y probar eso o si no hacemos y probamos nosotros.

2022-11-05 11:58 UTC, icarito commented
Gracias @lupomontero @mfdebian e @unjust por los comentarios, el PR quedó con los cambios solicitados. :pray:

2022-11-07 17:00 UTC, lupomontero approved these changes
:rocket: :star:

2022-11-07 19:28 UTC, mfdebian approved these changes
Qué **bello** trabajo colaborativo :smiling_face_with_tear:  mil gracias @icarito @unjust y @lupomontero :star2:

2022-11-07 19:35 UTC, merged