doc: removed heroku and added glitch & elephantSql
Laboratoria/bootcamp pull request #1252
Opened 2022-11-04 17:54 UTC by santiaguf

Se propone quitar Heroku de las opciones de despliegue ya que en 3 semanas finaliza su capa gratuita, una buena alternativa es Glitch que tiene soporte para node y expressJS. Adicionalmente se sugiere ElephantSQL para quienes deseen desplegar una base de datos relacional de Postgresql, este servicio también cuenta con una capa gratuita

2022-11-04 20:35 UTC, lupomontero commented on projects/04-burger-queen-api/README.md
> +* Si quieres trabajar con PostgreSql, [ElephantSQL](https://www.mongodb.com/cloud/atlas](https://www.elephantsql.com/plans.html)
```suggestion
* Si quieres trabajar con PostgreSql, [ElephantSQL](https://www.elephantsql.com/plans.html)
```

2022-11-04 20:36 UTC, lupomontero commented on projects/04-burger-queen-api/README.md
> +  nos permite alojar el servidor web express importando nuestro repositorio desde github
```suggestion
  nos permite alojar el servidor web Express importando nuestro repositorio desde GitHub.
```

2022-11-04 20:36 UTC, lupomontero approved these changes

2022-11-07 18:52 UTC, mfdebian requested changes

2022-11-07 18:52 UTC, mfdebian commented on projects/04-burger-queen-api/README.md
> +  nos permite alojar el servidor web Express importando nuestro repositorio desde GitHub.
```suggestion
  nos permite alojar el servidor web Express
importando nuestro repositorio desde GitHub.
```

Testeando a ver si manualmente me deja sugerir un cambio ya que por alguna razón github no me ofrece el panel para sugerir cambios, pero básicamente hay que dividir esta frase en dos líneas para que no se rompa la regla de ancho máximo esperado por nuestro linter de archivos markdown, como está ahora no está pasando el linteo y no llega a los tests.

2022-11-07 18:59 UTC, mfdebian approved these changes

2022-11-07 19:15 UTC, mfdebian requested changes

2022-11-07 19:15 UTC, mfdebian commented on projects/04-burger-queen-api/README.md
> +importando nuestro repositorio desde GitHub.
```suggestion
  importando nuestro repositorio desde GitHub.
```

2022-11-07 19:15 UTC, mfdebian approved these changes

2022-11-07 19:24 UTC, merged

2022-11-07 19:24 UTC, mfdebian commented
¡Mil gracias @santiaguf! :blush: un abrazo!