01 text analyzer
Laboratoria/bootcamp pull request #1372
Opened 2023-05-04 14:53 UTC by ssinuco

**Problema:**

Descentralizar el PF, es decir que una estudiante pueda agendar un PF con cualquier coach de Laboratoria y no esté limitada a agendar únicamente con las coaches asignadas a su cohorte.

**Hipótesis:**

Para que la descentralización pueda ser posible, los PF deben tener un formato y agenda estándar y las coaches deben tener lineamientos claros para de manera objetiva marcar o no un objetivo de aprendizaje como cumplido. Para lograr esto se debe establecer los criterios de aceptación de los proyectos así implique cerrar sus posibles soluciones.

**Experimento:**

Se ha creado el proyecto `01-text-analyzer` de nivel 1 como alternativa a `01-card-validation` y `01-cipher` para eliminar la complejidad que suele tener y la distracción que suele producir el algoritmo de lunh y la fórmula del cifrado cesar. En `01-text-analyzer` la estudiante implementará una aplicación web para calcular métricas de un texto que introduzca una usuaria, como el número de palábras, el número de caracteres, entre otras.

`01-text-analyzer` propone alcanzar los mismos objetivos de aprendizaje de `01-card-validation` y `01-cipher`. Para cada objetivo de aprendizaje se han fijado criterios mínimos de aceptación muy detallados. El proyecto cuenta con pruebas unitarias, análisis estático de código y pruebas end-to-end para validar que la estudiante ha cumplido con los criterios fijados. Estas pruebas se podrán ejecutar de manera manual en una terminal pero tambien se ejecutarán de manera automática coin una Github Action cada vez que se haga _push_ a la rama _main_ del repositorio.

**Resultados esperados:**

Para las estudiantes

- Solución del proyecto en 2 o 3 sprints
- Mayor concentración en aprender lo que no sabe y menor distracción practicando lo que sí
- Mayor claridad en lo que se espera que aprenda con los criterios mínimos de aceptación
- Feedback temprano y continuo sobre su cumplimiento de objetivos de aprendizaje y criterios mínimos de aceptación al ejecutar las pruebas del proyecto

Para las coaches

- Menor número de estudiantes que llegan a PF sin haber completado su proyecto o cumplido los criterios mínimos de aceptación
- Mayor claridad sobre los aprendizajes esperados de las estudiantes en el proyecto
- Conversaciones entre coach y estudiante durante el PF más enfocadas en los objetivos de aprendizaje no cumplidos según el resultado de las pruebas del proyecto
- Criterios más claros, objetivos y homógeneos entre todas las coaches para marcar o no un objetivo de aprendizaje como cumplido

2023-05-08 16:59 UTC, unjust requested changes
Ahora tengo que ver el proyecto en si. Creo mi feedback mas grande es:
* Separamos Objetivos de Aprendizaje y Criterios. Para el script puede funcionar. Tengo ideas que podemos agregar al Criterios con HTML semantico - pero creo primero hay que separarlos.
* No se si queremos agregar un parte ["para considerar Project Feedback"](https://github.com/Laboratoria/bootcamp/tree/main/projects/01-cipher#9-para-considerar-project-feedback) a final de doc.
Hicimos eso en algunos readmes (@merunga nos recomendo) para revisar con ellas que tiene que tener el proyecto
* Debemos que mencionar que tienen que cumplir un minimo de los fucnionalidades, o tienen que implementar todo? A veces ellas pueden extender mucho un proyecto intentando en hacer todo cuando quiza solo 2 o 3 historias de usuario seria suficiente.

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/.babelrc
> +  "plugins": ["@babel/plugin-transform-modules-commonjs"]
eso es solo para jest?

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/.editorconfig
> +indent_size = 2
porque incluimos eso? es para el linter?

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/.github/workflows/playwright.yml
> +    branches: [ main, master ]
creo podemos quitar `master` no?

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/README.md
> +
estamos cambiando [la estructura de README](https://github.com/Laboratoria/bootcamp/wiki/Anatom%C3%ADa-de-un-proyecto) con este proyecto. Podemos experimentar con eso pero hay que evaluar despues si quedamos con la estructura, si es mejor.

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/README.md
> +repositorio que contiene un _boilerplate_ con tests (pruebas). Un _boilerplate_
`contiene`

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/README.md
> +
Este seccion deberia separar en 2, para los Objetivos de Aprendizaje son generado con el [create-cohort-project script](https://github.com/Laboratoria/bootcamp/blob/main/scripts/README.md#scripts-para-coaches). Si necesitas ayuda en eso, me avisas

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/README.md
> +![npm run test](docs/images/npm-run-test.gif "npm run test")
Me gusta mas si ilustramos estes puntos con un pequeño Loom que habla como correr todos los tests. No es mucho esfuerzo, pero podemos hacer un follow up para convertir los gifs a un video bien cortito.

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/README.md
> +![npm run test](docs/images/npm-run-test.gif "npm run test")
Me gusta mas si ilustramos estes puntos con un pequeño Loom que habla como correr todos los tests. No es mucho esfuerzo, pero podemos hacer un follow up para convertir los gifs a un video bien cortito. Podemos convertir todo de este parte de pruebas en un guia con video.

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/docs/images/githubaction.gif
Creo vamos a tener una estructura de `guides/` con los proyectos. Quiza podemos renombrar `docs` a `guides`

2023-05-08 16:59 UTC, unjust commented on projects/01-text-analyzer/test/analyzer.spec.js
> +    it('debería retornar 0 para "' + TEST_TEST_EMPTY + '"', () => {
y si usamos template strings en lugar de `+`

2023-05-08 20:27 UTC, ssinuco commented
>     * Separamos Objetivos de Aprendizaje y Criterios. Para el script puede funcionar. Tengo ideas que podemos agregar al Criterios con HTML semantico - pero creo primero hay que separarlos.

Me parece que es mas claro que se asocia criterios de aceptacion con objetivos de aprendizaje. Los mantendria unidos.

 
>     * No se si queremos agregar un parte ["para considerar Project Feedback"](https://github.com/Laboratoria/bootcamp/tree/main/projects/01-cipher#9-para-considerar-project-feedback) a final de doc.

Si, de acuerdo con agregar esta seccion

>     * Debemos que mencionar que tienen que cumplir un minimo de los fucnionalidades, o tienen que implementar todo? A veces ellas pueden extender mucho un proyecto intentando en hacer todo cuando quiza solo 2 o 3 historias de usuario seria suficiente.

No lo pondria en el README, lo dejaria a criterio del equipo de coach de la cohort

2023-05-08 20:32 UTC, ssinuco commented on projects/01-text-analyzer/.editorconfig
> +indent_size = 2
El boilerplate de este proyecto esta basando en credit card validation. El archivo .editorconfig es el mismo de ese proyecto. Tendria que borrarlo y hacer pruebas para verificar si es necesario o no.

2023-05-08 20:33 UTC, ssinuco commented on projects/01-text-analyzer/.github/workflows/playwright.yml
> +    branches: [ main, master ]
Esta es la configuracion recomendada de playwright pero tienes razon, voy a eliminar master.

2023-05-08 20:33 UTC, ssinuco commented on projects/01-text-analyzer/README.md
> +
De acuerdo

2023-05-08 20:40 UTC, ssinuco commented on projects/01-text-analyzer/README.md
> +
@unjust tienes razon, hay un cambio de formato. Sin embargo con @merunga habiamos pensado que este proyecto fuera una excepcion teniendo en cuenta que se esta probando algo nuevo como los criterios de aceptacion. Me gustaria mantener unificada la seccion de objetivos de aprendizaje junto con los criterios de aceptacion, veo que estan muy relacionados.

2023-05-08 20:44 UTC, ssinuco commented on projects/01-text-analyzer/docs/images/githubaction.gif
De acuerdo

2023-05-08 20:45 UTC, ssinuco commented on projects/01-text-analyzer/test/analyzer.spec.js
> +    it('debería retornar 0 para "' + TEST_TEST_EMPTY + '"', () => {
@unjust lo tenia justo asi, pero lo cambie a + porque me parece que es mas claro para una estudiante que inicia a programar

2023-05-08 20:53 UTC, ssinuco commented on projects/01-text-analyzer/README.md
> +![npm run test](docs/images/npm-run-test.gif "npm run test")
@unjust creo que los loom estan quedando en cuentas individuales y se pueden perder cuando se eliminen estas cuentas. Creeria que deberia hacerse una cuenta de loom con un cuenta que no se pueda eliminar y alli subir todos los videos.

2023-05-08 20:53 UTC, ssinuco commented on projects/01-text-analyzer/.babelrc
> +  "plugins": ["@babel/plugin-transform-modules-commonjs"]
El boilerplate de este proyecto esta basando en credit card validation. El archivo .babelrc es el mismo de ese proyecto. No lo he probado, pero creeria que si, que esta es una configuracion para jest.

2023-05-09 15:06 UTC, unjust commented
@ssinuco no podemos romper el formato de a objetivos porque el script debe agregarlos automáticamente. Hay que sepáralos y de ahí trabajamos / escribimos abajo los criterios.

Entiendo porque quieres unirlos pero va a romper el script, y en mi opinión es más clara anunciarlos objetivos y en una sección aparte guiar los puntos específicos. Si quieres puede primero poner los criterios particulares y después listamos en la sección de OAs.

2023-05-09 22:49 UTC, Davichobits commented
![image](https://github.com/Laboratoria/bootcamp/assets/123121338/6f371b13-fede-44f9-9de1-7c4f46b864bf)
Cuando ejecuto npm run test:oas me sale lo de la captura, no lo que muestras en el gif. He descargado tu implementación de ejemplo. El resto de test se ejecutan normalmente. Hay algo que me esté faltando?

2023-05-09 22:52 UTC, Davichobits commented
Para poder ejecutar  `npm run test:e2e` es necesario instalar playwright primero. Eso no se especifica en el readme. Se lo deja sin especificar?

2023-05-16 17:48 UTC, unjust commented on projects/01-text-analyzer/.babelrc
> +  "plugins": ["@babel/plugin-transform-modules-commonjs"]
me parece que si, es para jest, pero seria bueno omitirlo y ver si sigue necesario porque estoy leyendo [comentarios que deberia ser automatica](https://github.com/babel/babel/issues/10240#issuecomment-513295914)

2023-05-16 19:04 UTC, unjust commented on projects/01-text-analyzer/src/analyzer.js
> +
en el readme o algun momento decimos que `getWordCount` y otras funciones tienen que hacer?
Quiza podemos poner 
```
TODO: contar las palabras en el text y devolver el numero
```

2023-05-16 19:04 UTC, unjust commented on projects/01-text-analyzer/src/index.js
> +import analyzer from './analyzer.js';
Un TODO sobre el DOM y interactividad?

2023-05-16 19:04 UTC, unjust commented on projects/01-text-analyzer/test/analyzer.spec.js
> +const TEST_TEXT_PUNCTUATION_MARKS = '.,;:"«»[]{}()¿?¡!-';
Como hablamos quiza algunas casos debe ser un Hacker Edition. Tambien hay que pensar si `dy!$!` califica como palabra o no, solo por tener algunas letras.
Lo de puro espacios no es tan dificil. Abri un Issue sobre eso https://github.com/ssinuco/01-text-analyzer/issues/1

2023-05-16 19:04 UTC, unjust commented on projects/01-text-analyzer/README.md
> +### Recursos y temas relacionados
creo vale pensar en cual recursos mas podemos agregar aqui - sobre `split` quiza? 

y no se si queremos agregar "Para pedir project feedback" con los requisitos que deben "pasar"

2023-05-16 19:05 UTC, unjust reviewed
Algunos puntos mas para considerar en el boilerplate y readme

2023-05-23 19:12 UTC, ssinuco commented
> Para poder ejecutar `npm run test:e2e` es necesario instalar playwright primero. Eso no se especifica en el readme. Se lo deja sin especificar?

Vale, lo agregue!

2023-05-23 19:12 UTC, ssinuco commented on projects/01-text-analyzer/src/analyzer.js
> +
Vale, lo agregue!

2023-05-23 19:13 UTC, ssinuco commented on projects/01-text-analyzer/test/analyzer.spec.js
> +const TEST_TEXT_PUNCTUATION_MARKS = '.,;:"«»[]{}()¿?¡!-';
Moví estos casos borde a Hacker Edition

2023-05-23 19:13 UTC, ssinuco commented on projects/01-text-analyzer/README.md
> +### Recursos y temas relacionados
No estoy seguro que deberia tener esta seccion

2023-05-23 19:14 UTC, ssinuco commented on projects/01-text-analyzer/README.md
> +![npm run test](docs/images/npm-run-test.gif "npm run test")
Deje los gifs mientras definimos que como centralizar los looms

2023-05-23 20:00 UTC, ssinuco commented on projects/01-text-analyzer/src/index.js
> +import analyzer from './analyzer.js';
Agregado!

2023-05-23 20:01 UTC, ssinuco commented
> ![image](https://user-images.githubusercontent.com/123121338/237235756-6f371b13-fede-44f9-9de1-7c4f46b864bf.png) Cuando ejecuto npm run test:oas me sale lo de la captura, no lo que muestras en el gif. He descargado tu implementación de ejemplo. El resto de test se ejecutan normalmente. Hay algo que me esté faltando?

Gracias por reportar! Ya esta solucionado!

2023-05-30 21:22 UTC, unjust commented
Ideas para el imagen de portada 
https://cdn-dfnaj.nitrocdn.com/xxeFXDnBIOflfPsgwjDLywIQwPChAOzV/assets/images/optimized/rev-7fa8f01/wp-content/uploads/2017/02/setup-word-cloud.png

https://www.codevertiser.com/reactjs-challenge-1-text-analyzer-tool/

https://cdn-media-1.freecodecamp.org/images/1*aIewSM1E9TbQvqxIvLy9jQ.png

https://media.licdn.com/dms/image/C4E12AQHIK9pBiHV6Lw/article-cover_image-shrink_423_752/0/1520106195237?e=1691020800&v=beta&t=H4C4V-5T5CCHXMqciUa3Wo_dsPyZx7bKc4Z4cbFS7xc

2023-05-30 21:46 UTC, unjust commented on projects/01-text-analyzer/read-only/test/e2e/app.spec.js
> +test.skip('Opcional:', () => {
Genial!

2023-05-30 21:55 UTC, unjust approved these changes
Me parece bien. Creo ay que agregar un imagen de portada.

2023-05-30 22:06 UTC, unjust commented on projects/01-text-analyzer/README.md
> +Un analizador de texto es una aplicación para extraer información útil de un
```suggestion

![Ejemplo text analyzer con word cloud](https://github.com/Laboratoria/bootcamp/assets/92090/597ec557-d6df-4130-bb71-d78cf2b9651c)

Un analizador de texto es una aplicación para extraer información útil de un
```

2023-05-30 22:09 UTC, unjust approved these changes

2023-05-31 14:56 UTC, unjust approved these changes

2023-05-31 14:58 UTC, merged