primer borrador readme mdLinks con hitos
Laboratoria/bootcamp pull request #1375
Opened 2023-05-11 21:35 UTC by Davichobits

2023-05-12 15:44 UTC, unjust reviewed
Me gusta la dirección de eso y el contenido. Quizá podemos trabajar en el google doc para ser más colaborativa y de ahí actualizar el Contenido a la rama.

2023-05-12 15:44 UTC, unjust commented on projects/04-md-links/README.md
> +Agrega un argumento más a la función mdLinks. El segundo parámetro recibirá un objeto **options** con el valor validate que deberá ser un booleano
En este revisión podemos tomar la libertad a decir que el segundo parámetro se llama `validate` y es tipo booleano. Cómo hablamos un objeto de opciones con sólo una propiedad no tiene mucho sentido.

2023-05-12 15:44 UTC, unjust commented on projects/04-md-links/README.md
> +### HITO 2: Javascript API con argumento "options"
Pensamos que los hitos son consecutiva o construye encima el anterior - quiza decimos "agrega validate al JavaScript api" o algo asi? Quizá no cambiamos el encabezado pero en los instrucciones hablamos asi?

2023-05-12 15:44 UTC, unjust commented on projects/04-md-links/README.md
> +* La función `mdLinks(path, options)` debe retornar una promesa (Promise) que resuelva a un arreglo (Array) de objetos (Object), donde cada objeto representa un link y contiene las siguientes propied
Hay que explicar que quedamos con la misma funcionalidad de anterior (cuando validate es undefined) Que es el mismo si validate es false o no pasamos validate.

2023-05-12 15:44 UTC, unjust commented on projects/04-md-links/README.md
> +Google
Piensas el output es mejor así con nuevas líneas? Para mi mejor si es más Compacto (solo una línea) . Pero también podemos mencionar que ellas tiene un poco libertad si al menos vemos la misma data

2023-06-15 19:42 UTC, unjust commented on projects/04-md-links/README.md
> +* En este proyecto hay que adoptar las convenciones que los proyectos open source de software usan para hacer seguimiento. Vas a usar Github projects con Issues y milestones para priorizar y organiza
`Issues y Milestones` o `issues y milestones`

2023-06-15 19:50 UTC, unjust commented on projects/04-md-links/README.md
> +* [ ] Pasa tests y linters (`npm test`).
"Que se implementa `--validate` y `--stats`"

Agregaria el 70% de funciones, branches etc ... coverage tests

2023-06-15 19:51 UTC, unjust commented on projects/04-md-links/README.md
> +### Otros recursos
Seria bueno revisar estes recursos, y quiza agrega algo de regex o los librerias marked etc

2023-06-15 19:52 UTC, unjust commented on projects/04-md-links/README.md
> +* Usando un módulo como markdown-it, que nos devuelve un arreglo de tokens que podemos recorrer para identificar los links.
hay que linkear esos librerias que mencionamos

2023-06-15 20:00 UTC, unjust commented on projects/04-md-links/README.md
> +## Tareas de este hito:
este encabezado deberia ser un nivel mas

Tenemos 
## 6. Hitos
### Hito 1

Entonces "Tareas de este hito" debe ser como `h4` , pero si no ve bien quiza podemos marcarlo en otra forma.
Y las tareas abajo son una lista semanticamente.

2023-06-15 20:04 UTC, unjust commented
Una pregunta que tengo es si ponemos todos los Hitos en el README asi, o si mencionamos los hitos en el README y linkearlo a un archivo milestones.md que explica todo eso.

Otro es si quiza el Hito de CLI movimos antes de Hito de recursividad ❓

2023-06-16 12:28 UTC, merunga reviewed
Gracias @Davichobits por este trabajo.
Comentarios:
- debemos elegir un termino unico para referirnos al modulo: o bien _libreria_ o bien _biblioteca_, pero creo q puede confundir un poco usarlas de manera indistinta
- todas los textos q hacen referencia a codigo, deberia estar formateado como tal, por ejemplo `new Promise()`
- creo q el readme está muy largo. @unjust creo q podemos avanzar asi, pero apuntaría a un nuevo issue donde en el README solo se detalla el problema, y que las guías de cómo atacar cada hito estuvieran fuera
- creo q es importante hacer un mdlint de manera temprana antes de mandar el PR

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +* [8.Pistas, tips y lecturas complementarias](#8-pistas-tips-y-lecturas-complementarias)
```suggestion
* [8. Pistas, tips y lecturas complementarias](#8-pistas-tips-y-lecturas-complementarias)
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +ligero muy popular entre desarrolladores. Es usado en muchísimas plataformas que
aquí usamos la palabra _developer_ porque no tiene género, si vamos a usar _desarrolladores_, creo q tendríamos que poner algo como
```suggestion
ligero muy popular entre desarrolladores y desarrolladoras. Es usado en muchísimas plataformas que
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +En este proyecto crearás una biblioteca de código que servirá como herramienta para analizar enlaces dentro de archivos Markdown. Esta biblioteca será accesible desde la línea de comandos (CLI) que p
Sabemos q _biblioteca_ es la traduccion correcta, pero es la mas usada? Personalmente creo q **libreria** es mas popular.
De todas formas deberíamos ser consistentes con el sustantivo q usemos

```suggestion
En este proyecto crearás una biblioteca de código que servirá como herramienta para analizar links dentro de archivos Markdown. Esta biblioteca será accesible desde la línea de comandos (CLI) que permitirá al usuario ejecutar la biblioteca directamente desde el terminal. Esta biblioteca, escrita en Node.js, se encargará de analizar los archivos en formato Markdown. La biblioteca será accesible al importarla desde el módulo publicado.
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +* En este proyecto hay que adoptar las convenciones que los proyectos open source de software usan para hacer seguimiento. Vas a usar Github projects con Issues y milestones para priorizar y organiza
```suggestion
* En este proyecto hay que adoptar las convenciones que los proyectos open source de software usan para hacer seguimiento. Vas a usar Github projects con **[issues](https://docs.github.com/es/issues)** y **[milestones](https://docs.github.com/es/issues/using-labels-and-milestones-to-track-work/about-milestones)** para priorizar y organizar el trabajo y hacer seguimiento de tu proceso. Dentro de cada milestone se crearán y asignarán los issues que cada quien considere necesarios.
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
>  * La **librería** y el **script ejecutable** (herramienta de línea de comando -
o _libreria_ en todos lados o _biblioteca_ en todos lados

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +  `readFileSync` para leer archivos. En su lugar, te sugerimos abordar este desafío de manera asíncrona utilizando `readFile`. Además, si utilizas el módulo [require("fs/promises")](https://nodejs.or
mmm, yo no estoy tan de acuerdo con esto... principalmente por 2 puntos:
- que no para todas el cambio a asincronia es tan simple
- que la asincronía oculta mucha de la claridad de la recursión, para mi recursión + asincron[ia = hacker edition

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +La función `mdLinks(path)` debe **retornar una promesa** que **resuelva a un arreglo** de objetos, donde cada objeto representa un link y contiene las siguientes propiedades:
```suggestion
La función `mdLinks(path)` debe **retornar una promesa** que **resuelva a un arreglo de objetos**, donde cada objeto representa un link y contiene las siguientes propiedades:
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +El valor de retorno de nuestra librería es una Promesa, no un array (la promesa resuelve un array). Prueba leyendo sobre las promesas y creando una por tu cuenta utilizando new Promise()
```suggestion
El valor de retorno de nuestra librería es una Promesa, no un array (la promesa resuelve un array). Prueba leyendo sobre las promesas y creando una por tu cuenta utilizando `new Promise()`
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +Empieza leyendo un solo archivo con una ruta fija y retorna su contenido. Para ver este contenido puedes utilizar un console.log al momento de ejecutar la función.
```suggestion
Empieza leyendo un solo archivo con una ruta fija y retorna su contenido. Para ver este contenido puedes utilizar un `console.log` al momento de ejecutar la función.
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +El módulo fs (FileSystem) te será de utilidad. Como mencionamos en las consideraciones técnicas, preferimos que uses readFile (en vez de readFileSync) Y recomendamos el módulo fs/promises para utiliz
```suggestion
El módulo `fs` (FileSystem) te será de utilidad. Como mencionamos en las consideraciones técnicas, preferimos que uses `readFile` (en lugar de `readFileSync`) y recomendamos el módulo `fs/promises` para utilizar estas funciones con promesas.
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +El La función `mdLinks(path, validate)`  debe recorrer todos los archivos existentes en la carpeta y por cada archivo .md que encuentre deberá extraer los links para mostrarlos en pantalla.
```suggestion
El La función `mdLinks(path, validate)` debe recorrer todos los archivos existentes en la carpeta y por cada archivo `.md` que encuentre deberá extraer los links para mostrarlos en pantalla. 
```

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +El proyecto se basa en un proceso lógico compuesto por diferentes pasos. Para comprender mejor lo que debes hacer y planificar tus tareas y objetivos, se recomienda desglosar el proceso en pasos y vi
```suggestion
El proyecto se basa en un proceso lógico compuesto por diferentes pasos. Para comprender mejor lo que debes hacer y planificar tus tareas y objetivos, se recomienda desglosar el proceso en pasos y visualizarlo mediante un diagrama de flujo o escribiendo pseudocódigo
```

Tenemos recursos para diagramas de flujo y/o pseudo codigo?
Además establecería q este proceso no puede durar más de un sprint

2023-06-16 12:28 UTC, merunga commented on projects/04-md-links/README.md
> +### Otros recursos
si, me parece q son demasiados recursos... quizas distribuirlos en cada hito para entender cuales son relevantes a qué feature?

2023-06-16 22:02 UTC, Davichobits commented on projects/04-md-links/README.md
> +* En este proyecto hay que adoptar las convenciones que los proyectos open source de software usan para hacer seguimiento. Vas a usar Github projects con Issues y milestones para priorizar y organiza
issues y milestones

2023-06-16 22:12 UTC, Davichobits commented on projects/04-md-links/README.md
> +#### Ejemplo (resultados como comentarios)
Solamente pondría "Ejemplo" como texto y ya?

2023-06-20 19:47 UTC, Davichobits commented on projects/04-md-links/README.md
> +* [ ] Pasa tests y linters (`npm test`).
"Que se implementa --validate y --stats" no tiene mucho sentido para mi. Le pondría mejor:  "Además acepta los parámetros `--validate` y `--stats`"

2023-06-20 19:53 UTC, Davichobits commented on projects/04-md-links/README.md
>  * La **librería** y el **script ejecutable** (herramienta de línea de comando -
Dentro del documento mayormente se escribe librería, así que dejaré con librería en todos lados.

2023-06-22 22:24 UTC, Davichobits commented on projects/04-md-links/README.md
> +  - Deberá ofrecer soporte para directorios que pueden contener otros directorios.
Especifiqué al final de cada requisito a que hitos pertenecen.

2023-06-26 22:46 UTC, DeysiVergara commented on projects/04-md-links/README.md
>  * `path`: Ruta **absoluta** o **relativa** al **archivo** o **directorio**.
Creo que podría comenzar con archivos en el primer hito y considerar el recorrido en directorios en otro hito, la recursión suele complicar a las estudiantes que mas les cuesta.

2023-06-26 23:00 UTC, DeysiVergara commented on projects/04-md-links/README.md
> +Por ejemplo, es recomendable escribir tests que invoquen la función `mdLinks` y comprueben que esta función resuelva con un arreglo con la información esperada. También es importante probar las otras
Valdrá la pena mencionar que también pueden hacer los tests individuales si tuvieran pequeñas funciones antes de la de mdlinks, para que vayan haciendo funciones y testeando a la par?

2023-06-27 16:27 UTC, unjust commented on projects/04-md-links/README.md
> +Por ejemplo, es recomendable escribir tests que invoquen la función `mdLinks` y comprueben que esta función resuelva con un arreglo con la información esperada. También es importante probar las otras
Creo con `También es importante probar las otras funciones que hayas escrito en tu código.` estamos sugeriendo eso, o crees hay algo adicional o mas clara @DeysiVergara ?

2023-06-27 19:27 UTC, DeysiVergara commented on projects/04-md-links/README.md
> +Por ejemplo, es recomendable escribir tests que invoquen la función `mdLinks` y comprueben que esta función resuelva con un arreglo con la información esperada. También es importante probar las otras
Lo digo por el grado de dificultad y porque integrar todo en la función suele ser de las ultimas cosas que hacen, en la redacción se siente priorizado la de mdlinks  y eso puede postergar el testeo. Quizás lo pondría al revés o como 'Es importante testear las funciones mientras a la par que se escriben, incluso antes y no olvidar testear la función mdlinks' .

2023-06-29 22:46 UTC, Davichobits commented
Voy a eliminar estos recursos:

```
### Tutoriales

* [learnyounode](https://github.com/workshopper/learnyounode)
* [how-to-npm](https://github.com/workshopper/how-to-npm)
* [promise-it-wont-hurt](https://github.com/stevekane/promise-it-wont-hurt)
```

Siento que las estudiantes tratan de seguir todo el curso, pensando que deben aprender cada tecnología a profundidad. Veré que se puede poner como recurso alternativo.

2023-06-30 18:52 UTC, unjust reviewed
Algunos comentarios. Tambien @DeysiVergara puede opinar.

2023-06-30 18:52 UTC, unjust commented on projects/04-md-links/README.md
>  * [¿Qué es Nodejs? Javascript en el Servidor - Fazt en YouTube](https://www.youtube.com/watch?v=WgSc1nv_4Gw)
eligeria solo uno "que es node"

2023-06-30 18:52 UTC, unjust commented on projects/04-md-links/README.md
> +* [Qué es NPM - freecode.camp](https://www.freecodecamp.org/espanol/news/que-es-npm/)
creo este es el mismo de tu yo y package json recurso, no? podemos elegir uno y ponerlo aqui.

2023-06-30 18:52 UTC, unjust commented on projects/04-md-links/README.md
> +* [Qué es la recursividad y cómo crear funciones recursivas - javascript.info](https://es.javascript.info/recursion)
me encanta este sitio! no sabia que tienen algo de recursividad.

2023-06-30 18:52 UTC, unjust commented on projects/04-md-links/README.md
> +* [Patrones para coincidencia de caracteres con expresiones regulares - mozilla.org ](https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Regular_expressions)
tenemos links arriba de `marked` y `jsdom` para pueden revisar si? no se si seria bueno repetirlos aqui o no 🤷‍♀️

2023-06-30 18:52 UTC, unjust commented on projects/04-md-links/README.md
>  * [Tú, yo y package.json](https://medium.com/noders/t%C3%BA-yo-y-package-json-9553929fb2e3)
quiza mover eso abajo

2023-07-03 21:10 UTC, Davichobits commented on projects/04-md-links/README.md
> +* [Qué es NPM - freecode.camp](https://www.freecodecamp.org/espanol/news/que-es-npm/)
Sin links diferentes pero si, el contenido es muy similar. Dejaré el de "Tu, yo y package.json..." en el hito 4

2023-07-03 21:14 UTC, Davichobits commented on projects/04-md-links/README.md
>  * [¿Qué es Nodejs? Javascript en el Servidor - Fazt en YouTube](https://www.youtube.com/watch?v=WgSc1nv_4Gw)
La mayoría son recursos tipo blog, entonces dejaré el video, para que haya variedad de formato.

2023-07-03 21:18 UTC, Davichobits commented on projects/04-md-links/README.md
>  * [Tú, yo y package.json](https://medium.com/noders/t%C3%BA-yo-y-package-json-9553929fb2e3)
Genial, los moví.

2023-07-03 21:18 UTC, DeysiVergara commented on projects/04-md-links/README.md
> +  El valor de retorno de nuestra librería es una Promesa, no un array (la
La redacción puede ser confusa, sobre todo cuando aun están descifrando que deben hacer, podría ser así:
"El valor de retorno de nuestra librería es una Promesa que resuelve un array".

2023-07-03 21:35 UTC, Davichobits commented on projects/04-md-links/README.md
> +Por ejemplo, es recomendable escribir tests que invoquen la función `mdLinks` y comprueben que esta función resuelva con un arreglo con la información esperada. También es importante probar las otras
Lo dejé así:

"Recuerda que es muy importante testear tus funciones puras, mientras escribes la función `mdLinks`. Y cuando ésta esté terminada, también deberás  testearla  al final asegurándote que resuelva un arreglo con la  información esperada. "

2023-07-03 21:36 UTC, Davichobits commented on projects/04-md-links/README.md
> +  El valor de retorno de nuestra librería es una Promesa, no un array (la
Buenísimo! gracias

2023-07-03 21:45 UTC, DeysiVergara commented on projects/04-md-links/README.md
> +* Asegúrate que el archivo es markdown
Se habla de leer y de trabajar con readfile y después de asegurarse que es un md, lo colocaría al revés. No necesitaríamos leer si no es md.

2023-07-05 04:25 UTC, Davichobits commented on projects/04-md-links/README.md
> +* Asegúrate que el archivo es markdown
Tienes razón Deysi, muchas gracias, corregí eso y agregué un par de pasos más.

2023-07-05 15:44 UTC, mfdebian commented on projects/04-md-links/README.md
> +de analizar los archivos en formato Markdown. La librería será accesible al
Creo que es un poco repetitivo el:

> una librería de código que servirá como herramienta
para analizar links dentro de archivos Markdown

y luego

> Esta librería, escrita en Node.js, se encargará
de analizar los archivos en formato Markdown

Quizás podemos ponerlo más tipo:
_En este proyecto crearás una librería de código que servirá como herramienta
para analizar links dentro de archivos Markdown. Esta librería, escrita en
Node.js, será accesible desde la línea de comandos (CLI) y permitirá a la
usuaria ejecutar la librería directamente desde la terminal._

2023-07-05 15:45 UTC, mfdebian commented on projects/04-md-links/README.md
> +importarla desde el módulo publicado.
Creo que hasta este punto no se ha hablado nada sobre publicarlo, y sobretodo, qué significa en este contexto publicar el módulo, y qué es NPM, diría que tendríamos que introducir eso antes de hablar de esa publicación!

2023-07-05 19:34 UTC, mfdebian requested changes
Por ahora creo que sólo tengo estos comentarios :sweat_smile: 

¡Mil gracias @Davichobits por todo tu trabajo!!

2023-07-05 19:34 UTC, mfdebian commented on projects/04-md-links/README.md
> +internamente ejecutará la función mdLinks que acabas de crear.
Diría que sería bueno que comencemos explicando en este hito que es aquí donde nuestro programa se transforma en una "librería", que es la que hemos estado mencionando anteriormente, quizás mencionar NPM incluso

2023-07-05 19:34 UTC, mfdebian commented on projects/04-md-links/README.md
> +##### `--validate`
Deberíamos estar moviendo esta info al Hito 2? o la vamos a dejar así separada?

2023-07-05 19:34 UTC, mfdebian commented on projects/04-md-links/README.md
> +existentes en la ruta y buscar los links en todos los archivos md que encuentre.
```suggestion
existentes en la ruta y buscar los links en todos los archivos markdown que encuentre.
```

2023-07-05 19:34 UTC, mfdebian commented on projects/04-md-links/README.md
> +Entre los recursos de este proyecto hay un video que te ayudará.
Se refiere a la sección de pistas, tips, etc...? Si es así agregaría un link a esa sección del README

2023-07-05 19:34 UTC, mfdebian commented on projects/04-md-links/README.md
> +##### `--stats`
Es esta la primera mención a la opción `stats` no? no debería ella ser también parte de un _hito_? :open_mouth:  creo que me marié un poco ya :laughing:

2023-07-05 19:34 UTC, mfdebian commented on projects/04-md-links/README.md
> +  link con una librería de DOM como JSDOM o Cheerio entre otras).
Agregaría los links de las herramientas que se mencionan

2023-07-05 19:34 UTC, mfdebian commented on projects/04-md-links/README.md
> +  regulares (RegExp).
También agregaría la opción de pasar el markdown a markup, donde los links serán etiquetas `<a>` quizás no es la más popular, pero sigue siendo una opción :grin:

2023-07-05 19:34 UTC, mfdebian requested changes
Por ahora creo que sólo tengo estos comentarios :sweat_smile: 

¡Mil gracias @Davichobits por todo tu trabajo!!

2023-07-06 15:41 UTC, unjust commented on projects/04-md-links/README.md
> +  mdLinks debería rechazarse con un error.
No diria `retornar` - `mdLinks` devuelva una Promesa que deberia recharzar con un error.
si queremos agregar el "que indique" - vale, pero quedamos con "recharzarse la Promesa con un error que indique..."

2023-07-06 15:44 UTC, unjust commented on projects/04-md-links/README.md
> +  `console.log()` al momento de ejecutar la función.
Ojo que queremos recomendar `readFile` que usa promesas. Entonces cualquier cambio seremos clara con eso.

2023-07-06 15:47 UTC, unjust commented on projects/04-md-links/README.md
> +un booleano **validate**. Este segundo parámetro será opcional.
Yo diria 
`Agregaremos un PARAMETRO más a la función `mdLinks` que se llama `validate`. Sera un ARGUMENTO opcional y su tipo de dato será `boolean`.` 😆

2023-07-06 15:49 UTC, unjust commented on projects/04-md-links/README.md
> +`mdLinks(path, validate)`
Si. Es algo que muchas de ellas investigan y hacen.

2023-07-06 15:54 UTC, unjust commented on projects/04-md-links/README.md
> +extraer los links para mostrarlos en pantalla.
No puedo ver el contexto de esta recomendacion. Depende si estamos hablando de CLI aqui. Solo agrega cuidado con "retornar" si estamos hablando de una promesa aqui.

2023-07-06 15:56 UTC, unjust commented on projects/04-md-links/README.md
> +##### `--validate`
Es una opcion de CLI entonces pertenece a este HITO y no la 2.

2023-07-06 15:57 UTC, unjust commented on projects/04-md-links/README.md
> +##### `--stats`
Creo este es parte de [un HITO 4](https://github.com/Laboratoria/bootcamp/blob/133d09d481b51b88908b3569ecb5d7368df89787/projects/04-md-links/README.md#hito-4---interfaz-de-l%C3%ADnea-de-comando)

2023-07-06 23:01 UTC, Davichobits commented on projects/04-md-links/README.md
> +de analizar los archivos en formato Markdown. La librería será accesible al
Genial Alpi, gracias!

2023-07-06 23:10 UTC, Davichobits commented on projects/04-md-links/README.md
> +importarla desde el módulo publicado.
Si además creo que estamos llenando npmjs de proyectos que muchas de las veces no están completos. Entonces mejor no publicarlos, si no que solamente sean instalables directamente desde github.

2023-07-07 15:31 UTC, mfdebian commented on projects/04-md-links/README.md
> +importarla desde el módulo publicado.
El publicar el paquete en NPM es uno de los objetivos generales de este proyecto, aunque esté incompleto o no terminado, es importante que las estudiantes durante el bootcamp conozcan el proceso de publicar su librería, yo no lo quitaría :pray:

2023-07-07 15:37 UTC, mfdebian commented on projects/04-md-links/README.md
> +  [aquí](https://nodejs.org/api/esm.html#enabling)
@unjust :open_mouth: me declaro ignorante, desconozco esas fricciones, como lo hago yo es simplemente poner `type: module` en el `package.json` y tener `node` en su versión `16` (que si pensamos que hoy en día ya estamos llegando a la 20, ya es prácticamente común tener, por ejemplo, [la versión LTS](https://nodejs.org/en) de hoy en día, que es la `18`) y nada más, pero en su experiencia dices que para las estudiantes les suele no funcionar?

2023-07-07 15:44 UTC, mfdebian commented on projects/04-md-links/README.md
> +  regulares (RegExp).
uff, estaba ya mareado revisando el PR en esa vista de review, pero me refería a esta sección:

`transformar el markdown a HTML usando algo como [marked](https://github.com/markedjs/marked)
  y de ahí extraer los link con una librería de DOM como [JSDOM](https://github.com/jsdom/jsdom)`
  
 que sí está un poco más arriba :sweat_smile: la pasé demasiado rápido al parecer

2023-07-07 20:19 UTC, Davichobits commented on projects/04-md-links/README.md
> +Comienza haciendo la versión más sencilla de mdlinks. Crea una función que
Perfecto, gracias!

2023-07-07 20:29 UTC, Davichobits commented on projects/04-md-links/README.md
> +##### `--stats`
Correcto, está en el hito 4

2023-07-07 20:39 UTC, Davichobits commented on projects/04-md-links/README.md
> +* [Patrones para coincidencia de caracteres con expresiones regulares - mozilla.org ](https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Regular_expressions)
Si están esos recursos más arriba, y no le veo necesario repetirlos. Yo dejaría esta sección de Otros Recursos como eso, otros recursos, no los mismos

2023-07-07 21:34 UTC, Davichobits commented on projects/04-md-links/README.md
> +  [aquí](https://nodejs.org/api/esm.html#enabling)
Yo personalmente les digo a las estudiantes que pueden utilizar commonJS para que practiquen otra forma de importar/exportar. En el mundo laboral seguramente trabajarán con un código heredado y van a encontrar commonJS y ya les será familiar. Con el resto de proyectos ya podrán utilizar ES modules. 

Aunque, estoy haciendo la implementación de mdlinks ahora y veo que solamente cambiando el package.json, como comenta Alpi, es suficiente para utilizar los ES modules. Le voy a dejar de la siguiente manera:

Para que practiques otra forma de importar y exportar módulos en Node.js, puedes utilizar CommonJS con `require`, que es el formato de módulos original de Node.js.  Si deseas utilizar los ES Modules (import/export), asegúrate de configurar correctamente tu archivo package.json agregando la propiedad "type" con el valor "module". Esto permitirá que Node.js reconozca y utilice el formato de módulos ES.

2023-07-10 17:38 UTC, unjust reviewed
Algunas cosas pequeños. Me parece 💯 
Que piensa @mfdebian ?

2023-07-10 17:38 UTC, unjust commented on projects/04-md-links/README.md
> +usando Node.js. prenderemos cómo buscar y leer archivos, cómo hacer consultas
```suggestion
usando Node.js. Aprenderemos cómo buscar y leer archivos, cómo hacer consultas
```

2023-07-10 17:38 UTC, unjust commented on projects/04-md-links/README.md
> +  de Jest para ES Modules aún es experimental)
Yo quedaria con el contenido anterior y solo agrego el frase final de Jest. Prefiero que ellas busca en la documentacion la manera hacer la configuracion - porque he visto que a veces no es solo cambiar "type" para su sistema y version

2023-07-10 17:38 UTC, unjust commented on projects/04-md-links/README.md
> +  método `resolve()`.
porque cambiamos eso? siempre usan `isAbsolute` para comprobarlo antes de convertirlo, no?

2023-07-10 17:38 UTC, unjust commented on projects/04-md-links/README.md
> +Al finalizar, podrás compartir esta biblioteca utilizando NPM (Node Package
```suggestion
Al finalizar, podrás instalar esta biblioteca utilizando NPM (Node Package
```

2023-07-10 19:15 UTC, Davichobits commented on projects/04-md-links/README.md
> +  de Jest para ES Modules aún es experimental)
Perfecto

2023-07-10 19:17 UTC, Davichobits commented on projects/04-md-links/README.md
> +  método `resolve()`.
Lo que pasa es que resolve() devuelve la ruta absoluta, sin importar si inicialmente ya era absoluta, o relativa. Entonces la verificación anterior está de más.

2023-07-14 21:40 UTC, mfdebian requested changes
No alcancé a cubrir todos los hitos, así que queda pendiente una segunda parte de este review, pero por ahora esas son mis notas :blush: 


¡¡GRACIAS @Davichobits y @unjust !! :partying_face:

2023-07-14 21:40 UTC, mfdebian commented on projects/04-md-links/README.md
> +  [aquí](https://nodejs.org/api/esm.html#enabling). Algo a tener en
```suggestion
  [aquí](https://nodejs.org/api/packages.html#determining-module-system). Algo a tener en
```

personalmente yo cambiaría el link por este, que es más directo en presentarte las 3 opciones que tienes para que node lo interprete como ESM

2023-07-14 21:40 UTC, mfdebian commented on projects/04-md-links/README.md
> +* Para este proyecto, te recomendamos utilizar los módulos CommonJS con
Perdonen lo cargante :rofl: pero yo aún no me convenzo de esto, creo que no deberíamos estar empujando que usen CJS por sobre ESM :see_no_evil:

¿Qué les parece dejarlo un poco más abierto? Tipo: _Existen dos opciones para trabajar con JS usando Node, CSJ y ESM... etc..._ :grin: o no?

2023-07-14 21:40 UTC, mfdebian commented on projects/04-md-links/README.md
> +  de Jest para ES Modules el mismo que aún es experimental.
```suggestion
  [aquí](https://nodejs.org/api/packages.html#determining-module-system).
  Además, tendrás que configurar Jest para ello también, siguiendo los
  [siguientes pasos](https://jestjs.io/docs/ecmascript-modules).
  Ten en consideración que Jest considera esto aún como un _feature
  experimental_.
```

Encontré un poco rara la redacción, quizás lo podemos dejar así?

2023-07-14 21:40 UTC, mfdebian commented on projects/04-md-links/README.md
> +  podrás aprovechar las promesas con `readFile`.
```suggestion
  módulo `fs/promises`, podrás utilizar la versión promisificada de las
  funciones como
  [`readFile`](https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fspromisesreadfilepath-options).
```

Este link es mucho más directo al ejemplo. Creo que ese sitio de documentación es difícil de navegar para las estudiantes.

2023-07-14 21:40 UTC, mfdebian commented on projects/04-md-links/README.md
> +un booleano **validate**. Este segundo parámetro será opcional.
que se llamará `validate` nomas le cambiaría :blush:  (y quitaría las mayúsculas :ninja: )

2023-07-14 21:40 UTC, mfdebian commented on projects/04-md-links/README.md
> +**Valor que resuelve la promesa con validate = false ó undefined:**
hmmm, tienes razón, quizás hay un valor en que exista la posibilidad de que sea `undefined` :thinking:

2023-07-14 21:40 UTC, mfdebian commented on projects/04-md-links/README.md
> +extraer los links para mostrarlos en pantalla.
de acuerdo, quizás cambiar la palabra _retornarlos_ por _resolverlos_?

2023-07-14 23:12 UTC, unjust commented on projects/04-md-links/README.md
> +* Para este proyecto, te recomendamos utilizar los módulos CommonJS con
Hm me parece estamos bailando alrededor la tema. Quiza no vamos a decir directamente "recomendamos" - pero creo es importante decir que `require` no requiere (jaja) configuracion extra. En verdad he gastado tiempo en office hours ayudando ellas configurar ESM y despues jest. Y para mi es mas directo a usar `require` todavia.

2023-07-14 23:29 UTC, unjust commented
Gracias @mfdebian . @Davichobits y yo los revisamos tus comentarios el lunes. Hay que cerrar los comentarios el lunes porque ya pasa 2 meses en review 🙀

2023-07-18 17:51 UTC, unjust commented
![Screen Shot 2023-07-18 at 12 49 45 PM](https://github.com/Laboratoria/bootcamp/assets/92090/23b2b21f-c54f-48e7-9dfa-f6d130a00669)

Me encanta!

Hablamos en planning hoy para cerrar este issue y actualizar tu sitio de documentacin, De ahi recopilamos data!
Hay que resolver los conflictos. Gracias @Davichobits.

2023-07-19 23:15 UTC, mfdebian requested changes
Mil gracias querido @Davichobits :partying_face: 

Dejé algunas sugerencias de cambios y también algunos comentarios! Me avisan cualquier cosa :blush:

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/02-milestone.md
> +un booleano que se llamará _validate_. Este segundo parámetro será opcional.
```suggestion
Agrega un argumento más a la función `mdLinks`. El segundo parámetro recibido
será un booleano que se llamará `validate`. Este segundo parámetro será
opcional.
```

Siento que se lee un poquito mejor así

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/02-milestone.md
> +OJO: _el valor anterior es el mismo que el del hito 1_
Temas de estilos, pero yo personalmente quitaría esas llamadas de atención con mayúsculas, creo que es mejor poner algo como:

_Recuerda que el valor anterior es el mismo que el del hito 1_

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/02-milestone.md
> +(resultados como comentarios)
```suggestion

```

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/03-milestone.md
> +existentes en la carpeta y por cada archivo `.md` que encuentre deberá
```suggestion
existentes en la carpeta y por cada archivo Markdown que encuentre deberá
```

Para no limitarnos sólo a la extensión `.md`

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/03-milestone.md
> +que no sean md. En este caso debes la función debe ignorarlos. (Crea una
```suggestion
Debes tener en cuenta que la carpeta puede contener archivos que no sean
Markdown. En este caso debes la función debe ignorarlos. (Crea una
```

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/03-milestone.md
> +(resultados como comentarios)
```suggestion

```

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/03-milestone.md
> +### **HITO 3:** Buscando dentro de una carpeta
Debería rendirme con lo de llamarle 'directorio' a las carpetas? :rofl: creo que es un lenguaje más común a encontrar en la documentación de otras herramientas, pero si soy el único que lo piensa, o si prefieren 'carpeta' porque es más cercano a la experiencia de usuaria de las estudiantes, mejor lo dejamos así :+1:

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/04-milestone.md
> +para poderlo instalar a con npm.
```suggestion
para poderlo instalar con [NPM](https://www.npmjs.com/).
```

Les parece incluir un link aquí? si no, igual hay que arreglar ese typo! ('_instalar a con_').

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/04-milestone.md
> +línea de comando como una interfaz que podamos importar con require para
```suggestion
línea de comando como una interfaz que podamos importar para
```

sólo para no confundir a las estudiantes que hayan escogido trabajarlo con ESM

2023-07-19 23:15 UTC, mfdebian commented on projects/04-md-links/docs/05-milestone.md
> +Entre los [recursos](#hito-5) de este proyecto hay una página
Creo que me perdí un poco, en este contexto, a dónde te envía ese link? :grin:

2023-07-20 22:03 UTC, Davichobits commented on projects/04-md-links/docs/01-milestone.md
> +(resultados como comentarios)
Se queda, tal vez para las estudiantes pueda que no sea tan obvio.

2023-07-21 17:26 UTC, unjust commented on projects/04-md-links/README.md
> +  utilizar ES Modules `(import/export)`, puedes hacerlo, pero ten en cuenta que
```suggestion
* Para este proyecto, hay que decidir si vas a utilizar los módulos CommonJS
o ES Modules. Los módulos CommonJS usan la síntaxis `require`
y es el formato de módulos original de Node.js.
Si prefieres utilizar ES Modules `(import/export)`, puedes hacerlo,
pero ten en cuenta que
```

2023-07-21 17:32 UTC, unjust commented on projects/04-md-links/README.md
> +* Usando un custom renderer de la librería marked (new marked.Renderer()).
```suggestion
* Usando un [custom renderer de la librería marked](https://marked.js.org/using_pro#renderer) (new marked.Renderer()).
```

2023-07-21 17:33 UTC, unjust commented on projects/04-md-links/README.md
> +readdirSync) y path.
```suggestion
específicas de Node que puedes explorar, como los módulos `fs` (`readFile`,
`readdirSync`) y `path`.
```

2023-07-21 17:37 UTC, unjust commented on projects/04-md-links/README.md
> +    directorios. (Hitos 1 al 5)
```suggestion
  - El módulo debe exportar una función que cumpla con la interfaz (API)
    requerida. (Hito 1)
  - Deberá implementar el soporte para archivos individuales. (Hito 1)
  - Deberá implementar la funcionalidad de validación. (Hitos 1 y 2)
  - Deberá ofrecer soporte para directorios. (Hitos 1 al 3)
  - Deberá ofrecer soporte para directorios que pueden contener otros
    directorios. (Hitos 1 al 5)
```

2023-07-21 17:40 UTC, unjust commented on projects/04-md-links/README.md
> +  md-links en el path (configurado en el package.json)
```suggestion
* [ ] un CLI (Command Line Interface) que se ejecuta sin errores
  y tiene el output esperado. Además acepta los parámetros
  `--validate` y `--stats`. Y expone un ejecutable
  md-links en el path (configurado en el `package.json`)
* [ ] el CLI es instalable de través de NPM (Node
    Package Manager). (Hitos 1 al 4)
```

2023-07-21 17:45 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +Argumento:
```suggestion
Parámetro:
```

2023-07-21 17:45 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +* `path`: Ruta **absoluta** o **relativa** al **archivo** o **directorio**.
```suggestion
* `path`: Ruta **absoluta** o **relativa** al **archivo** .
```

2023-07-21 17:49 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +* Crea una promesa
```suggestion
* Crea una Promesa
```

2023-07-21 17:49 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +* Asegúrate que el archivo es markdown
```suggestion
* Asegúrate que el archivo es Markdown
```

2023-07-21 17:50 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +  por ejemplo: .js, .txt, .doc, etc
```suggestion
  por ejemplo: `.js`, `.txt`, `.doc`, etc
```

2023-07-21 17:50 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +  mdLinks debería rechazarse con un error.
```suggestion
  `mdLinks()` debería rechazarse con un error.
```

2023-07-21 17:51 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +* Encuentra los links dentro del documento.
```suggestion
* Encuentra los links dentro del documento
```

2023-07-21 17:51 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +  arreglo para que la función de mdLinks los pueda resolver.
```suggestion
  arreglo para que la función de `mdLinks` los pueda resolver.
```

2023-07-21 18:01 UTC, unjust commented on projects/04-md-links/docs/01-milestone.md
> +  it('debería resolver un arreglo con 3 links para un archivo .md con 3 links', ()=>{
```suggestion
  it('debería resolver un arreglo con 3 links para un archivo .md con 3 links', () => {
```

2023-07-21 18:07 UTC, unjust commented on projects/04-md-links/docs/02-milestone.md
> +un booleano que se llamará _validate_. Este segundo parámetro será opcional.
```suggestion
Agrega un parámetro más a la función `mdLinks` que se llamará _validate_ y que recibirá un valor booleano. _validate_ será un argumento opcional.
```

2023-07-21 18:08 UTC, unjust commented on projects/04-md-links/docs/02-milestone.md
> +un booleano que se llamará _validate_. Este segundo parámetro será opcional.
creo estamos mezclando mucho parametro y argumento - yo diria que agregamos un parametro al signature de funcion. Pero _recibimos_ argumentos, los valores.

2023-07-21 18:09 UTC, unjust commented on projects/04-md-links/docs/02-milestone.md
> +* path: Ruta absoluta o relativa al archivo o directorio. Si la ruta pasada
```suggestion
* `path`: Ruta absoluta o relativa al archivo o directorio. Si la ruta pasada
```

2023-07-21 18:09 UTC, unjust commented on projects/04-md-links/docs/02-milestone.md
> +* validate: Booleano que determina si se desea validar los links encontrados.
```suggestion
* `validate`: Booleano que determina si se desea validar los links encontrados.
```

2023-07-21 18:10 UTC, unjust commented on projects/04-md-links/docs/02-milestone.md
> +mdLinks("./some/example.md", true )
```suggestion
mdLinks("./some/example.md", true)
```

2023-07-21 18:12 UTC, unjust commented on projects/04-md-links/docs/02-milestone.md
> +# **HITO 2:** Javascript API con segundo parámetro opcional "validate"
```suggestion
# **HITO 2:** Javascript API con segundo parámetro "validate"
```

2023-07-21 18:15 UTC, unjust commented on projects/04-md-links/docs/03-milestone.md
> +usuaria será capaz de pasar un directorio como ruta.
```suggestion
usuaria será capaz de pasar un directorio como ruta para el argumento `path`.
```

2023-07-21 18:16 UTC, unjust commented on projects/04-md-links/docs/03-milestone.md
> +mdLinks("./some/dir", true )
```suggestion
mdLinks("./some/dir", true)
```

2023-07-21 18:17 UTC, unjust commented on projects/04-md-links/docs/03-milestone.md
> +  El resultado sería: /home/Laboratoria/test
```suggestion
 ` /home/Laboratoria/`

  `./test`

  El resultado sería: `/home/Laboratoria/test`
```

2023-07-21 18:18 UTC, unjust commented on projects/04-md-links/docs/04-milestone.md
> +Este paquete deberá estar documentado en un repositorio público con un package.json
```suggestion
Este paquete deberá estar documentado en un repositorio público con un package.json
```
```suggestion
Este paquete deberá estar documentado en un repositorio público con un `package.json`
```

2023-07-21 18:19 UTC, unjust commented on projects/04-md-links/docs/04-milestone.md
> +solo debe identificar el archivo markdown (a partir de la ruta que recibe como
```suggestion
solo debe identificar el archivo Markdown (a partir de la ruta que recibe como
```

2023-07-21 18:20 UTC, unjust commented on projects/04-md-links/docs/04-milestone.md
> +internamente ejecutará la función mdLinks que acabas de crear.
```suggestion
internamente ejecutará la función `mdLinks` que acabas de crear.
```

2023-07-21 18:22 UTC, unjust commented on projects/04-md-links/docs/04-milestone.md
> +# **HITO 4:** - Interfaz de Línea de comando
```suggestion
# **HITO 4:** - Interfaz de Línea de Comando (CLI)
```

2023-07-21 18:24 UTC, unjust commented on projects/04-md-links/docs/04-milestone.md
> +En este hito, crearás un paquete ejecutable de tu código, el mismo que
```suggestion
En este hito, crearás un script ejecutable, un script que
```

2023-07-21 18:26 UTC, unjust commented on projects/04-md-links/docs/04-milestone.md
> +```
antes de hablar de la instalación etc yo hablaria de todo de CLI y opciones etc. Y el "paquete" o iinstalacion a final

2023-07-21 18:29 UTC, unjust commented on projects/04-md-links/docs/05-milestone.md
> +recursividad y ver algunos ejemplos (ojo con concepto de casos base)
```suggestion
recursividad y ver algunos ejemplos (ojo con concepto de casos base).
```

2023-07-21 18:29 UTC, unjust commented on projects/04-md-links/docs/05-milestone.md
> +existentes en la ruta y buscar los links en todos los archivos markdown que
```suggestion
existentes en la ruta y buscar los links en todos los archivos Markdown que
```

2023-07-21 21:23 UTC, Davichobits commented on projects/04-md-links/docs/02-milestone.md
> +# **HITO 2:** Javascript API con segundo parámetro opcional "validate"
El segundo parámetro no era opcional? Y si no se lo pone por defecto tiene un valor de false?

2023-07-22 17:33 UTC, unjust commented on .mdlintignore
> +node_modules/
hay que revertir estes cambios
`git checkout upstream/next -- <path/to/file>`

2023-07-22 17:33 UTC, unjust commented on package.json
> +    "mdlint": "mdlint projects\\04-md-links\\docs\\05-milestone.md",
y revertir eso

2023-07-22 17:38 UTC, unjust commented on projects/04-md-links/docs/02-milestone.md
> +# **HITO 2:** Javascript API con segundo parámetro opcional "validate"
esta bien quedamos asi

2023-07-24 23:04 UTC, unjust approved these changes
Gran trabajo! Gracias @Davichobits

2023-07-25 00:39 UTC, merged