cambio de replit a codepen y glitch
Laboratoria/bootcamp pull request #1397
Opened 2023-06-08 23:50 UTC by DeysiVergara

Estor colocando dos opciones en vez de replit, si elegimos una de ellas, haría un tutorial para reemplazar el de replit,  o dos tutoriales, si se elige los dos.

2023-06-09 14:37 UTC, mfdebian requested changes
Muchas gracias @DeysiVergara :raised_hands: !!

Antes de aprobarlo, te puedo pedir que también agregues este cambio en la versión en portugués del README del proyecto? así de una los mergeamos y quedan ambos actualizados! :blush:

2023-06-09 17:14 UTC, unjust requested changes
Algunas cosas mas y me parece que hay que reemplazar aqui: 

https://github.com/Laboratoria/bootcamp/blob/f52206ce725f89b124479ad4701d9c00ab8e9480/projects/00-trivia/README.md?plain=1#L288

2023-06-09 17:14 UTC, unjust commented on projects/00-trivia/README.md
> +<!--[Tutorial Glitch]()-->
este comentario es intencional?

2023-06-09 17:14 UTC, unjust commented on projects/00-trivia/README.md
>  #### Si estás dando tus primeros pasos en el Desarrolo Web
```suggestion
#### Si estás dando tus primeros pasos en el Desarrollo Web
```

2023-06-09 17:14 UTC, unjust commented on projects/00-trivia/README.md
>  #### Si estás dando tus primeros pasos en el Desarrolo Web
se que no tocaste pero, podemos aprovechar ;-)

2023-06-09 18:06 UTC, DeysiVergara commented on projects/00-trivia/README.md
> +<!--[Tutorial Glitch]()-->
Si, lo deje para recordar que hay que hacer un tutorial de uso de glitch y de codepen también, como el que estaba colocado ahí de replit.

2023-06-12 16:59 UTC, unjust commented on projects/00-trivia/README.md
> +<!--[Tutorial Glitch]()-->
ok! Entonces quiza poner `TODO` en los comentarios, voy agregar un issue

2023-06-12 17:01 UTC, unjust commented on projects/00-trivia/README.md
> +<!--[Tutorial Glitch]()-->
#1399

2023-06-19 17:34 UTC, unjust approved these changes
Gracias!

2023-06-19 20:26 UTC, DeysiVergara reviewed
Cambios en readme pt

2023-06-19 20:28 UTC, DeysiVergara reviewed
revisado

2023-06-19 21:28 UTC, mfdebian approved these changes
LGTM :star:

2023-06-19 21:29 UTC, merged