Primer intenta a cambiar `copy` para solo copiar archivos de idioma eligido
Laboratoria/bootcamp pull request #1425
Opened 2023-06-29 18:27 UTC by unjust

Ahora el script solo analiza que el README de idioma (pt o es) esta copiado, pero si hay otros markdowns, copian todo.

Ahora
sin `--locale` o `--locale=es` : `README.md` -> `README.md`
`--locale=pt` : `README.pt.md` -> `README.md`

no importa el local : `otroArchivo.md` y `otroArchivo.pt.md` estan copiada tal cual. [Ejemplo en un proyecto actual](https://github.com/Laboratoria/DEV005-burger-queen-api/tree/main/guides)

Seria bueno solo copiar solo las de idioma, entonces con markdowns adicionales tambien solo copiamos
sin `--locale` o `--locale=es` : `otroArchivo.md` -> `otroArchivo.md`
`--locale=pt` : `otooArchivo.pt.md` -> `otroArchivo.md`

Casos para considerar:
* markdowns que solo tiene una version en la idioma por defecto tal vez debe ser copiado/disponible no importa el local
* links en markdowns de una idioma no deberia agregar la idioma a su extension (por ejemplo un link de `README.md` hacia `otroArchivo.pt.md` solo deberia decir `otroArchivo.md`

2023-07-07 16:06 UTC, mfdebian reviewed
gracias @unjust :partying_face: 

hay algo que falte en este PR? se invoca una función llamada `getAllFilesInDir` pero no está declarada en el script, será que se quedó afuera de este PR? :grin:

2023-07-14 22:48 UTC, unjust commented on scripts/create-cohort-project.mjs
> +import { getFilesWithLocales, defaultLocale, supportedLocales } from './script-utils.mjs';
he creado un archivo mas para `script-utils` pensando que necesitaba crear mas que una funcion.
no se que piensan. un beneficio es estoy exportando el funcion y hice un test.

Tambien no se si tenemos locales definido en otro lado donde puedo importar como `defaultLocale` y `supportedLocales`

2023-07-17 17:40 UTC, mfdebian requested changes
@unjust aún me toca seguir revisándolo bien, pero tengo que hacer almuerzo ahora y luego tenemos reuniones, pero quería mostrarte que me está arrojando error

Al ejecutar el comando de la siguiente manera:

`$ npm run create-cohort-project projects/04-burger-queen-api ~/Documents/ DEV100`

Donde no estoy pasando un atributo `locale`, y por lo tanto el comportamiento esperado es el de que utilice como `locale` la `defaultLocale` (`'es'`), sin embargo, debido a la condición descrita que mencioné dentro de este review, a la función `getFilesWithLocales` sólo le llega al array `[ 'pt' ]` como argumento, pero en cualquier caso, el error que me arroja es el siguiente:

```sh
[Error: ENOENT: no such file or directory, unlink '/home/alpi/Documents/DEV100-burger-queen-api//home/alpi/Documents/DEV100-burger-queen-api/README.pt.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/home/alpi/Documents/DEV100-burger-queen-api//home/alpi/Documents/DEV100-burger-queen-api/README.pt.md'
}
```

Que al parecer tiene relación con un `join` _extra_ que se debe estar invocando por ahí en la función `getFilesWithLocales`, ahorita después de almuerzo y saliendo de las reus lo reviso con más detenimiento, que no he alcanzado a llegar a esa función, para arreglar ese comportamiento.

Por lo demás, muchas gracias por el orden y claridad del código, estoy de acuerdo con tener una `defaultLocale` y también con que _comencemos_ a crear esa suite de tests para los scripts! :blush:

2023-07-17 17:40 UTC, mfdebian commented on scripts/create-cohort-project.mjs
> +  const files = getFilesWithLocales(repoDir, supportedLocales.filter((loc) => loc !== (opts.locale || defaultLocale)));
Al haber llegado a esta parte, entiendo que el comportamiento esperado sería el de usar `defaultLocale` como segundo argumento para la función `getFilesWithLocales` ya que en el paso anterior tenemos esta condición:
`if (opts.locale && opts.locale !== defaultLocale)`
donde, si existe locale y además, es _distinta_ al `defaultLocale` vamos a enviar ese valor recibido por la CLI que se encuentra guardado en `opts.locale`, entonces para esta siguiente invocación, que no cumple esa condición, es decir, no se recibió un valor por la CLI y por lo tanto `opts.locale` no tiene asignado un valor (o el valor recibido es igual a `defaultLocale`), la sentencia:
`supportedLocales.filter((loc) => loc !== (opts.locale || defaultLocale))` va a filtrar esos locales (`['es', 'pt']`), buscando uno que sea distinto a `opts.locale` (condición que siempre será `true` si `opts.locale` está vacío), _o_ que sea _distinto_ a `defaultLocale`, es decir, como resultado siempre dará la string `pt`.

Si lo estoy entiendo bien, en este punto esperábamos invocar la función cuando no se cumpla la condición descrita anteriormente (`if (opts.locale && opts.locale !== defaultLocale)`), para ese comportamiento, creo que podríamos hacer algo como:

```suggestion
    if(!opts.locale) {
      const files = getFilesWithLocales(repoDir, defaultLocale);
    }
```

2023-07-17 21:12 UTC, unjust commented on scripts/create-cohort-project.mjs
> +  const files = getFilesWithLocales(repoDir, supportedLocales.filter((loc) => loc !== (opts.locale || defaultLocale)));
1. En el bloque de linea 84 hay paso uno
```
if (opts.locale && opts.locale !== defaultLocale) {
    const files = getFilesWithLocales(repoDir, [ opts.locale ]);
    await Promise.all(files.map(
      (filepath) => rename(`${repoDir}/${filepath}`, `${repoDir}/${filepath.replace(`.${opts.locale}`, '')}`))
    );
```
Estamos haciendo un rename de los archivos que tiene el locale elegido para reemplazar los por defecto.
entonces si elegimos `pt` hacemos rename de `README.pt.md` -> `README.md`

2. El segundo paso es para limpiar / borrar los otros archivos que quedan y tienen locales no elegidos. Ahora es un poco raro porque solo tenemos [`es` ,`pt`] como locales, y tampoco usamos `es` como extension en los archivos. 
Pero imaginemos un caso cuando tengamos por ejemplo 3 idiomas [`es`, `en`, `pt`], y elegimos `en`.
En esta caso si hay un `opts.locale` pero todavia vamos necesitar borrar los archivos de otros idiomas - [`es`, `pt`] por eso hay el filter para sacar el locale elegido de supportedLocales y usar el arreglor de locales que quedan para el segundo argumento en 91 .

2023-07-17 21:14 UTC, unjust commented on package.json
>      "pretest": "npm run mdlint && npm run eslint && npm run validate && npm run test:topics",
deberia agregar `test:scripts` aqui?

2023-07-17 21:55 UTC, unjust commented
Quiero comentar que un comportamiento de este script (como antes) es que si hay un documento que solo tiene version en el local por defecto, va a quedar en el proyecto resultado - no importa si no esta en el locale elegido.
Osea, siempre va a tener un version de cada documento en el proyecto, pero si no hay un version en la idioma elegido, este documento va a estar en español.

```
README.md
README.pt.md
Guia.md
```
resulta en
```
README.md  (pt)
Guia.md         (es)
```

2023-07-24 21:12 UTC, mfdebian requested changes
Quizás podemos seguir revisándolo con más detenimiento, pero creo que haciendo ese cambio se comporta como esperamos y los tests siguen pasando :blush: 

Muchas muchas gracias @unjust :pray:

2023-07-24 21:12 UTC, mfdebian commented on scripts/create-cohort-project.mjs
> +      (filepath) => rename(`${repoDir}/${filepath}`, `${repoDir}/${filepath.replace(`.${opts.locale}`, '')}`))
En este punto me estaba dando el siguiente error:

```
[Error: ENOENT: no such file or directory, rename '/home/alpi/Documents/PORT-burger-queen-api//home/alpi/Documents/PORT-burger-queen-api/README.pt.md' -> '/home/alpi/Documents/PORT-burger-queen-api//home/alpi/Documents/PORT-burger-queen-api/README.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/home/alpi/Documents/PORT-burger-queen-api//home/alpi/Documents/PORT-burger-queen-api/README.pt.md',
  dest: '/home/alpi/Documents/PORT-burger-queen-api//home/alpi/Documents/PORT-burger-queen-api/README.md'
}
```

Como la función `getFilesWithLocales` ya hace un `join` entre el `dir` y los archivos, cuando llegamos a esta línea, al hacer `map`, `filepath` ya contiene la ruta completa (`/home/alpi/Documents/PORT-burger-queen-api/README.pt.md`) y por lo tanto no es necesario hacer `${repoDir}/${filepath}` en el `rename()`

```suggestion
  return await Promise.all(files.map(
    (filepath) => rename(`${filepath}`, `${filepath.replace(`.${opts.locale}`, '')}`))
```

2023-07-31 14:46 UTC, unjust commented on scripts/create-cohort-project.mjs
> +      (filepath) => rename(`${repoDir}/${filepath}`, `${repoDir}/${filepath.replace(`.${opts.locale}`, '')}`))
@mfdebian quiero recrear este comportamiento y error antes de aplicar el Commit para entenderlo.
Es raro porque yo pruebo después cada cambio y no logro tener un error.

2023-07-31 15:36 UTC, mfdebian commented on scripts/create-cohort-project.mjs
> +      (filepath) => rename(`${repoDir}/${filepath}`, `${repoDir}/${filepath.replace(`.${opts.locale}`, '')}`))
podríamos verlo juntxs hoy en la tarde! :blush:

2023-07-31 19:39 UTC, unjust commented on scripts/create-cohort-project.mjs
> +      (filepath) => rename(`${repoDir}/${filepath}`, `${repoDir}/${filepath.replace(`.${opts.locale}`, '')}`))
Llegamos ver que hay un diferencia entre los paths absoluto  y relativos (por ejemplo correrlo con`~/Documentes` vs `../../temp`). Aun los paths fueron repetidos con los dos, pero un path absoluto tiro el error.

2023-08-07 21:55 UTC, mfdebian approved these changes
No he alcanzado a revisar todo el código :grimacing: se me fue la hora :sweat_smile: , quizás mañana juntas lo podemos ver con más detalles, pero probando su uso, ahora sí tiene el comportamiento esperado :smile: 

Mil gracias @unjust !!

2023-08-07 23:33 UTC, merged