chore(project): Redo Adrian's changes to `burger-queen-api-client` README in ES and adds the correpsonding changes in the PT README as well
Laboratoria/bootcamp pull request #1470
Opened 2023-07-19 16:34 UTC by mfdebian

Sin querer, al darle merge a #1455 hemos pisado los cambios propuestos por @Adrian0617 y revisados por @unjust en #1418 

Este cambio soluciona eso.

Además, este PR closes #1469

2023-07-19 17:58 UTC, paclaraujo commented on projects/04-burger-queen-api-client/README.pt.md
> +Este projeto deve ser "resolvido" em duplas e, para trabalhar com o backend,
```suggestion
Este projeto deve ser implementado em duplas e, para trabalhar com o backend,
```

2023-07-19 17:58 UTC, paclaraujo commented on projects/04-burger-queen-api-client/README.pt.md
> +para a API implantada. Essa situação costuma ocorrer no Desenvolvimento Web,
```suggestion
para a API implantada. Isso costuma ocorrer no Desenvolvimento Web, em duas principais situações: 

- quando é necessário avançar com a implementação do frontend enquanto as
pessoas responsáveis pelo backend ainda estão no processo de design;
- quando é necessário avançar com a implementação do frontend enquanto as
pessoas responsáveis pelo backend ainda estão desenvolvendo a  API a ser consumida quando o projeto estiver pronto
para ser implantado e passar para a produção;
```

2023-07-19 17:58 UTC, paclaraujo commented on projects/04-burger-queen-api-client/README.pt.md
> +para a API implantada. Essa situação costuma ocorrer no Desenvolvimento Web,
Pensei em separar mais, pois o parágrafo muito longo dificulta a interpretação do texto. O que acha?

2023-07-19 18:52 UTC, unjust commented
LGTM, pero @paclaraujo tiene cambios.

2023-07-19 20:05 UTC, mfdebian commented on projects/04-burger-queen-api-client/README.pt.md
> +para a API implantada. Essa situação costuma ocorrer no Desenvolvimento Web,
vou fazer esse commit no meu local para consertar o linter do markdown! obrigado @paclaraujo :partying_face:

2023-07-19 20:54 UTC, unjust requested changes
Lo más importante es hay duplicación en PT

2023-07-19 20:54 UTC, unjust commented on projects/04-burger-queen-api-client/README.pt.md
> +* Quando é necessário avançar com a implementação do frontend enquanto as
Esta duplicada

2023-07-19 20:54 UTC, unjust commented on projects/04-burger-queen-api-client/README.md
> +de la API a consumir cuando el proyecto ya sea desplegado y pase a producción.
Yo para con "de la API." Porque pienso el frase es un poco largo Pero solo mi opinión

2023-07-20 15:10 UTC, unjust requested changes

2023-07-20 15:10 UTC, unjust commented on projects/04-burger-queen-api-client/README.md
> +de la API a consumir cuando el proyecto ya sea desplegado y pase a producción.
```suggestion
pasarte a la API desplegada. Esta situación suele ocurrir en Desarrollo Web
cuando se necesita avanzar con la implementación del frontend mientras las
personas encargadas del backend aún están en proceso de diseño o desarrollo
de la API.
```

2023-07-20 15:10 UTC, unjust commented on projects/04-burger-queen-api-client/README.md
> +de la API a consumir cuando el proyecto ya sea desplegado y pase a producción.
Yo para con "de la API." Pienso el frase es un poco largo y no pierda significa si para asi.

2023-07-20 15:10 UTC, unjust commented on projects/04-burger-queen-api-client/README.pt.md
> +  consumida quando o projeto estiver pronto para ser implantado e passar para a produção.
```suggestion
para a API implantada. Isso costuma ocorrer no Desenvolvimento Web, quando é necessário avançar com a implementação do frontend enquanto as
  pessoas responsáveis pelo backend ainda estão desenvolvendo a API.
```

2023-07-20 15:10 UTC, unjust commented on projects/04-burger-queen-api-client/README.pt.md
> +  consumida quando o projeto estiver pronto para ser implantado e passar para a produção.
En verdad no estaba duplicada tal cual, solo que repite casi la misma idea

2023-07-20 23:06 UTC, unjust commented
@mfdebian acabo de buscar y si agregamos los traducciones de PT en este issue. entonces no se que paso?
https://github.com/Laboratoria/bootcamp/pull/1452/files

2023-07-21 19:07 UTC, unjust approved these changes

2023-07-21 19:25 UTC, merged