fix: quita swagger como api y agregar la opcion desplegar el mock vercel
Laboratoria/bootcamp pull request #1513
Opened 2023-08-03 17:17 UTC by unjust

El link de swagger nunca fue un api desplegada. quita este link como opcion de api.
Tambien estoy agregando que pueden desplegar su mock (agrega un recurso de vercel en ingles 🤔 ).

@ssinuco si podemos estar en acuerdo de espanol voy haciendo la traducion en portugues.

- [x] redaccion en espanol
- [ ] portugues

2023-08-08 15:55 UTC, ssinuco approved these changes
Me parece que esta perfecto!

2023-08-08 19:11 UTC, mfdebian requested changes
Pequeñas correcciones ortográficas :blush:

2023-08-08 19:11 UTC, mfdebian commented on projects/04-burger-queen-api-client/README.md
> +  que hemos desarrollado. El mock API debería comportar como definimos
```suggestion
  que hemos desarrollado. Esta mock API debería comportarse de la manera definida
```

2023-08-08 19:11 UTC, mfdebian commented on projects/04-burger-queen-api-client/README.md
> +  Aquí es [un ejemplo como desplegar tu mock con Vercel.](https://medium.com/@phillipnzaujunior/unleashing-the-power-of-mock-apis-deploying-your-fake-rest-api-to-vercel-d1cbd95b4452)
```suggestion
  Aquí hay [un ejemplo como desplegar tu mock con Vercel.](https://medium.com/@phillipnzaujunior/unleashing-the-power-of-mock-apis-deploying-your-fake-rest-api-to-vercel-d1cbd95b4452)
```

2023-08-15 19:47 UTC, unjust commented
Aun tengo que hacer los cambios y agregar portugues.

2023-08-22 17:08 UTC, mfdebian approved these changes
LGTM :star: 

gracias @unjust !

2023-08-22 19:58 UTC, merged