Add Text Analyzer README in Portuguese
Laboratoria/bootcamp pull request #1537
Opened 2023-08-24 19:55 UTC by ChristianRL23

- Se hizo una revisión completa de que todo estuviera en portugués y con la misma estructura del .md original.
- Se revisó cada uno de los links que habían y se actualizaron algunos a recursos en portugués.

2023-08-24 21:15 UTC, MaferAlmeida commented on projects/01-text-analyzer/README.pt.md
Nessa parte, retirar o ponto de exclamação antes do Sim, teria somente no fim da frase:

Nota: para simplificar as funcionalidades, definiremos palavras como grupos de caracteres separados por espaços. Por exemplo, as palavras no texto de entrada ¡Sim, você pode fazer isso! são quatro:

    ¡Sim,

2023-08-24 21:41 UTC, unjust requested changes
Diria que hacimos los cambios a los tests en otra rama, es un issue aparte
https://github.com/Laboratoria/bootcamp/issues/1533

Y los cambios seria en el mismo `analyzer.spec.js` (no `en.js`, me gusta la idea pero por ahora hacer los cambios en el spec original.)

2023-08-25 16:01 UTC, unjust reviewed
Sin el "diff" de como fue `analyzer.spec.js` anterior - al menos el ingles me parece bien, solo un comentario. Pero cuando hay el diff (no creamos nuevo spec.en pero solo aplicamos los cambios a spec.js) puedo ver mejor la traduccion de antes/despues

2023-08-25 19:05 UTC, unjust commented on projects/01-text-analyzer/test/analyzer.spec.js
> +const TEST_TEXT_NUMBERS = 'If I have 8 apples and i buy 2 more, how many apples do i have in total?';
```suggestion
const TEST_TEXT_NUMBERS = 'If I have 8 apples and I buy 2 more, how many apples do I have in total?';
```

2023-08-25 19:06 UTC, unjust commented on projects/01-text-analyzer/test/analyzer.spec.js
> +    it('debería should return 2.9 for "' + TEST_TEXT_DECIMALS + '"', () => {
```suggestion
    it('should return 2.9 for "' + TEST_TEXT_DECIMALS + '"', () => {
```

2023-08-25 19:08 UTC, unjust approved these changes
LGTM!

2023-08-26 20:09 UTC, unjust commented
Por favor @ChristianRL23 integrar estes cambios a tu rama https://github.com/ChristianRL23/bootcamp/pull/1/files
Y de ahi puedes conseguir otra approval de una persona y hacer el merge.

2023-08-28 16:59 UTC, unjust approved these changes
Gracias por corregir los de mdlint.

2023-08-28 17:00 UTC, merged